export const DATA = [
  { q: { vi:"Một tổ chức muốn cải tiến quy trình kiểm thử dựa trên một mô hình có các mức trưởng thành rõ ràng và các vùng quy trình được định nghĩa cụ thể cho đánh giá chính thức bên ngoài. Mô hình nào phù hợp nhất?",
        en:"An organization wants to improve its test process using a model with clearly defined maturity levels and specific process areas for formal external assessment. Which model fits best?",
        ja:"組織は、明確な成熟度レベルと正式な外部アセスメント用の特定プロセスエリアを持つモデルでテストプロセスを改善したい。最も適したモデルはどれですか?" },
    options: [
      { vi:"TMMi vì là mô hình phân bậc với các mức trưởng thành và vùng quy trình cho đánh giá chính thức", en:"TMMi because it is a staged model with maturity levels and process areas for formal assessment", ja:"正式アセスメント用の成熟度レベルとプロセスエリアを持つステージモデルであるTMMi" },
      { vi:"CTP vì là mô hình phi mức tập trung quy trình then chốt", en:"CTP because it is a non-level model focused on critical processes", ja:"重要プロセスに焦点を当てる非レベルモデルのCTP" },
      { vi:"STEP vì là mô hình liên tục không dùng mức", en:"STEP because it is a continuous model without levels", ja:"レベルを使わない継続的モデルのSTEP" },
      { vi:"IDEAL vì cung cấp các mức trưởng thành để đánh giá", en:"IDEAL because it provides maturity levels for assessment", ja:"アセスメント用の成熟度レベルを提供するIDEAL" } ],
    answer: 0,
    exp: { vi:"TMMi là mô hình phân bậc gồm năm mức trưởng thành với các vùng quy trình cụ thể, thiết kế cho đánh giá chính thức. CTP và STEP là mô hình phi mức; IDEAL là khung cải tiến chứ không phải mô hình trưởng thành.",
          en:"TMMi is a staged model with five maturity levels and specific process areas designed for formal assessment. CTP and STEP are non-staged; IDEAL is an improvement framework, not a maturity model.",
          ja:"TMMiは5つの成熟度レベルと特定プロセスエリアを持つステージモデルで、正式アセスメント用に設計されています。CTPとSTEPは非ステージ型、IDEALは成熟度モデルではなく改善フレームワークです。" } },

  { q: { vi:"TPI Next khác biệt cơ bản với TMMi ở điểm nào khi triển khai cải tiến?",
        en:"How does TPI Next fundamentally differ from TMMi when driving improvement?",
        ja:"改善を推進する際、TPI NextはTMMiと根本的にどう異なりますか?" },
    options: [
      { vi:"TPI Next bắt buộc đạt toàn bộ một mức trước khi sang mức kế tiếp", en:"TPI Next requires achieving an entire level before moving to the next", ja:"TPI Nextは次のレベルへ進む前にレベル全体の達成を要求する" },
      { vi:"TPI Next dùng các khu vực chính với ma trận trưởng thành cho phép cải tiến từng khu vực độc lập", en:"TPI Next uses key areas with a maturity matrix allowing independent improvement per area", ja:"TPI Nextは、エリアごとに独立して改善できる成熟度マトリクスを持つキーエリアを使用する" },
      { vi:"TPI Next không có khái niệm mức trưởng thành nào", en:"TPI Next has no concept of maturity levels at all", ja:"TPI Nextには成熟度レベルの概念が全くない" },
      { vi:"TPI Next chỉ áp dụng cho kiểm thử tự động", en:"TPI Next applies only to test automation", ja:"TPI Nextはテスト自動化にのみ適用される" } ],
    answer: 1,
    exp: { vi:"TPI Next là mô hình liên tục với 16 khu vực chính, mỗi khu vực có nhiều mức (controlled, efficient, optimizing), cho phép cải tiến độc lập theo khu vực. TMMi phân bậc yêu cầu hoàn tất mức trước.",
          en:"TPI Next is a continuous model with 16 key areas, each having levels (controlled, efficient, optimizing), enabling independent per-area improvement. TMMi is staged and requires completing levels in order.",
          ja:"TPI Nextは16のキーエリアを持つ継続的モデルで、各エリアにレベル（管理・効率・最適化）があり、エリアごとの独立改善を可能にします。TMMiはステージ型でレベルを順に完了する必要があります。" } },

  { q: { vi:"Trong khung IDEAL, giai đoạn nào thiết lập cam kết lãnh đạo, phạm vi và bối cảnh cho chương trình cải tiến?",
        en:"In the IDEAL framework, which phase establishes management commitment, scope and context for the improvement program?",
        ja:"IDEALフレームワークで、経営層のコミットメント、スコープ、コンテキストを確立するフェーズはどれですか?" },
    options: [
      { vi:"Diagnosing", en:"Diagnosing", ja:"診断（Diagnosing）" },
      { vi:"Establishing", en:"Establishing", ja:"確立（Establishing）" },
      { vi:"Initiating", en:"Initiating", ja:"開始（Initiating）" },
      { vi:"Learning", en:"Learning", ja:"学習（Learning）" } ],
    answer: 2,
    exp: { vi:"Giai đoạn Initiating thiết lập bối cảnh kinh doanh, cam kết lãnh đạo và hạ tầng cho chương trình. Diagnosing đánh giá hiện trạng, Establishing lập kế hoạch, Learning rút kinh nghiệm.",
          en:"The Initiating phase sets the business context, management commitment and infrastructure for the program. Diagnosing assesses the current state, Establishing plans, and Learning captures lessons.",
          ja:"開始フェーズはビジネスコンテキスト、経営層のコミットメント、インフラを確立します。診断は現状評価、確立は計画、学習は教訓収集です。" } },

  { q: { vi:"Sau khi hoàn tất một chu kỳ cải tiến, nhóm phân tích những gì đã và chưa hiệu quả rồi điều chỉnh cách tiếp cận cho chu kỳ sau. Đây là giai đoạn nào của IDEAL?",
        en:"After completing an improvement cycle, the team analyzes what worked and adjusts the approach for the next cycle. Which IDEAL phase is this?",
        ja:"改善サイクル完了後、チームは何が有効だったかを分析し次のサイクルへアプローチを調整します。これはIDEALのどのフェーズですか?" },
    options: [
      { vi:"Acting", en:"Acting", ja:"実行（Acting）" },
      { vi:"Diagnosing", en:"Diagnosing", ja:"診断（Diagnosing）" },
      { vi:"Establishing", en:"Establishing", ja:"確立（Establishing）" },
      { vi:"Learning", en:"Learning", ja:"学習（Learning）" } ],
    answer: 3,
    exp: { vi:"Giai đoạn Learning đánh giá toàn bộ chu kỳ, ghi nhận bài học và cải thiện chính quy trình cải tiến cho lần sau, khép kín vòng lặp IDEAL.",
          en:"The Learning phase reviews the whole cycle, records lessons and improves the improvement process itself for the next round, closing the IDEAL loop.",
          ja:"学習フェーズはサイクル全体をレビューし、教訓を記録し、次回に向けて改善プロセス自体を改善して、IDEALループを閉じます。" } },

  { q: { vi:"Một quản lý kiểm thử muốn KPI cho hiệu quả phát hiện lỗi. Chỉ số nào phản ánh tốt nhất khả năng phát hiện lỗi trước khi ra sản xuất?",
        en:"A test manager wants a KPI for defect detection effectiveness. Which metric best reflects finding defects before production?",
        ja:"テストマネージャーは欠陥検出の有効性のKPIを望む。本番前に欠陥を発見する能力を最もよく反映する指標はどれですか?" },
    options: [
      { vi:"Defect Detection Percentage (DDP) — tỷ lệ lỗi tìm trước phát hành trên tổng số lỗi", en:"Defect Detection Percentage (DDP) - defects found pre-release over total defects", ja:"欠陥検出率（DDP）—総欠陥数に対するリリース前検出欠陥の割合" },
      { vi:"Tổng số ca kiểm thử đã thực thi", en:"Total number of test cases executed", ja:"実行したテストケースの総数" },
      { vi:"Số giờ kiểm thử trên mỗi ca", en:"Test hours per test case", ja:"テストケースあたりのテスト時間" },
      { vi:"Số lượng tester trong nhóm", en:"Number of testers in the team", ja:"チーム内のテスター数" } ],
    answer: 0,
    exp: { vi:"DDP (còn gọi DRE) đo tỷ lệ lỗi phát hiện trước phát hành trên tổng lỗi (trước cộng sau phát hành), phản ánh trực tiếp hiệu quả phát hiện. Các chỉ số còn lại đo hoạt động chứ không đo hiệu quả.",
          en:"DDP (also DRE) measures defects found before release over total defects (pre plus post release), directly reflecting detection effectiveness. The others measure activity, not effectiveness.",
          ja:"DDP（DREとも）は、総欠陥数（リリース前＋後）に対するリリース前検出欠陥の割合を測定し、検出の有効性を直接反映します。他は活動量であり有効性ではありません。" } },

  { q: { vi:"Khi thiết kế bộ KPI cho quản lý kiểm thử, nguyên tắc quan trọng nhất để tránh hành vi lệch lạc là gì?",
        en:"When designing test management KPIs, what is the most important principle to avoid dysfunctional behaviour?",
        ja:"テストマネジメントのKPIを設計する際、機能不全な行動を避けるための最も重要な原則は何ですか?" },
    options: [
      { vi:"Chỉ dùng một KPI duy nhất để đơn giản hóa", en:"Use a single KPI to keep it simple", ja:"単純化のため単一KPIのみ使う" },
      { vi:"Dùng bộ KPI cân bằng, gắn với mục tiêu và không khuyến khích tối ưu cục bộ gây hại", en:"Use a balanced set tied to goals that does not incentivize harmful local optimization", ja:"目標に紐づき、有害な局所最適化を促さないバランスの取れたセットを使う" },
      { vi:"Chọn KPI dễ thu thập nhất bất kể ý nghĩa", en:"Pick the easiest KPI to collect regardless of meaning", ja:"意味に関係なく最も収集しやすいKPIを選ぶ" },
      { vi:"Đặt mục tiêu KPI càng cao càng tốt để tạo áp lực", en:"Set KPI targets as high as possible to create pressure", ja:"プレッシャーを生むため目標をできる限り高く設定する" } ],
    answer: 1,
    exp: { vi:"Một KPI đơn lẻ dễ bị lợi dụng. Bộ KPI cân bằng, gắn mục tiêu kinh doanh giúp tránh việc tối ưu một chỉ số bằng cách hy sinh chất lượng thực; ví dụ đếm số ca kiểm thử có thể khuyến khích viết ca nông.",
          en:"A single KPI is easily gamed. A balanced set tied to business goals avoids optimizing one metric at the expense of real quality; e.g. counting test cases can encourage shallow tests.",
          ja:"単一KPIは容易にゲーム化されます。ビジネス目標に紐づくバランスの取れたセットは、実際の品質を犠牲にした一指標の最適化を防ぎます。例えばテストケース数の計測は浅いテストを助長します。" } },

  { q: { vi:"Một tổ chức nhỏ, dự án ngắn, muốn cải tiến nhanh mà không cần đánh giá chính thức tốn kém. Cách tiếp cận cải tiến nào phù hợp nhất?",
        en:"A small organization with short projects wants quick improvement without costly formal assessment. Which improvement approach fits best?",
        ja:"短期プロジェクトの小規模組織が、コストのかかる正式アセスメントなしで迅速に改善したい。最も適したアプローチはどれですか?" },
    options: [
      { vi:"Mô hình tham chiếu tiến trình như TMMi với đánh giá đầy đủ", en:"A process reference model such as TMMi with full assessment", ja:"完全アセスメントを伴うTMMiのようなプロセス参照モデル" },
      { vi:"Áp dụng cả TMMi và TPI Next đồng thời", en:"Apply both TMMi and TPI Next simultaneously", ja:"TMMiとTPI Nextを同時に適用する" },
      { vi:"Mô hình phân tích dựa trên đo lường và phân tích nguyên nhân gốc tại chỗ", en:"An analytical model based on measurement and local root-cause analysis", ja:"測定とローカルな根本原因分析に基づく分析型モデル" },
      { vi:"Chờ cho tổ chức lớn hơn rồi mới cải tiến", en:"Wait until the organization grows before improving", ja:"組織が大きくなるまで改善を待つ" } ],
    answer: 2,
    exp: { vi:"Cách tiếp cận phân tích (phân tích nguyên nhân gốc, phân tích dữ liệu lỗi, GQM) cho phép cải tiến nhanh, chi phí thấp, phù hợp tổ chức nhỏ. Mô hình tham chiếu tiến trình đòi hỏi đầu tư đánh giá lớn hơn.",
          en:"An analytical approach (root-cause analysis, defect data analysis, GQM) enables fast, low-cost improvement suited to small organizations. Process reference models require larger assessment investment.",
          ja:"分析型アプローチ（根本原因分析、欠陥データ分析、GQM）は、小規模組織に適した迅速で低コストの改善を可能にします。プロセス参照モデルはより大きなアセスメント投資を必要とします。" } },

  { q: { vi:"Trong TMMi, vùng quy trình 'Test Policy and Strategy' thuộc mức trưởng thành nào?",
        en:"In TMMi, the process area 'Test Policy and Strategy' belongs to which maturity level?",
        ja:"TMMiで、プロセスエリア「テストポリシーと戦略」はどの成熟度レベルに属しますか?" },
    options: [
      { vi:"Mức 2 - Managed", en:"Level 2 - Managed", ja:"レベル2 - 管理された" },
      { vi:"Mức 4 - Measured", en:"Level 4 - Measured", ja:"レベル4 - 測定された" },
      { vi:"Mức 5 - Optimization", en:"Level 5 - Optimization", ja:"レベル5 - 最適化" },
      { vi:"Mức 3 - Defined", en:"Level 3 - Defined", ja:"レベル3 - 定義された" } ],
    answer: 3,
    exp: { vi:"'Test Policy and Strategy' là vùng quy trình ở TMMi mức 3 (Defined), cùng Test Lifecycle and Integration, Test Training. Mức 2 gồm Test Planning, Monitoring & Control, Design & Execution, Environment.",
          en:"'Test Policy and Strategy' is a TMMi Level 3 (Defined) process area, alongside Test Lifecycle and Integration and Test Training. Level 2 covers Test Planning, Monitoring & Control, Design & Execution, Environment.",
          ja:"「テストポリシーと戦略」はTMMiレベル3（定義された）のプロセスエリアで、テストライフサイクルと統合、テスト訓練と共にあります。レベル2はテスト計画、監視・制御、設計・実行、環境を含みます。" } },

  { q: { vi:"Chính sách kiểm thử khác với chiến lược kiểm thử ở điểm nào?",
        en:"How does a test policy differ from a test strategy?",
        ja:"テストポリシーはテスト戦略とどう異なりますか?" },
    options: [
      { vi:"Chính sách nêu mục tiêu và giá trị cấp cao của tổ chức về kiểm thử; chiến lược mô tả cách tiếp cận chung để đạt mục tiêu đó", en:"Policy states high-level organizational objectives and values for testing; strategy describes the general approach to achieve them", ja:"ポリシーはテストの高レベルな組織目的と価値を述べ、戦略はそれを達成する一般的アプローチを記述する" },
      { vi:"Chính sách mô tả kỹ thuật thiết kế ca kiểm thử; chiến lược nêu triết lý tổ chức", en:"Policy describes test design techniques; strategy states organizational philosophy", ja:"ポリシーはテスト設計技法を記述し、戦略は組織哲学を述べる" },
      { vi:"Chúng đồng nghĩa và có thể thay thế nhau", en:"They are synonymous and interchangeable", ja:"両者は同義で置き換え可能である" },
      { vi:"Chính sách chỉ dành cho kiểm thử tự động", en:"Policy applies only to automated testing", ja:"ポリシーは自動テストにのみ適用される" } ],
    answer: 0,
    exp: { vi:"Test policy là tuyên bố cấp cao về mục tiêu, giá trị và cam kết của tổ chức với kiểm thử. Test strategy mô tả cách tiếp cận tổng quát (mức thử, kỹ thuật, tiêu chí) để hiện thực hóa chính sách đó.",
          en:"A test policy is a high-level statement of the organization's objectives, values and commitment to testing. A test strategy describes the general approach (levels, techniques, criteria) to realize that policy.",
          ja:"テストポリシーは、テストに対する組織の目的、価値、コミットメントの高レベルな声明です。テスト戦略は、そのポリシーを実現する一般的アプローチ（レベル、技法、基準）を記述します。" } },

  { q: { vi:"Một quản lý cần ước lượng ROI của việc đầu tư 200.000 USD vào cải tiến, dự kiến giảm chi phí lỗi sản xuất 300.000 USD/năm. ROI năm đầu là bao nhiêu?",
        en:"A manager estimates ROI of a 200,000 USD improvement investment expected to reduce production defect costs by 300,000 USD/year. What is the first-year ROI?",
        ja:"マネージャーは、本番欠陥コストを年間300,000ドル削減する見込みの200,000ドルの改善投資のROIを見積もる。初年度のROIは?" },
    options: [
      { vi:"150%", en:"150%", ja:"150%" },
      { vi:"50%", en:"50%", ja:"50%" },
      { vi:"33%", en:"33%", ja:"33%" },
      { vi:"200%", en:"200%", ja:"200%" } ],
    answer: 1,
    exp: { vi:"ROI = (lợi ích - chi phí) / chi phí = (300.000 - 200.000) / 200.000 = 0,5 = 50%. ROI đo lợi ích ròng trên chi phí, không phải tổng lợi ích trên chi phí.",
          en:"ROI = (benefit - cost) / cost = (300,000 - 200,000) / 200,000 = 0.5 = 50%. ROI measures net benefit over cost, not gross benefit over cost.",
          ja:"ROI =（便益 - コスト）/ コスト =（300,000 - 200,000）/ 200,000 = 0.5 = 50%。ROIは総便益ではなく純便益をコストで割ったものです。" } },

  { q: { vi:"Khi trình bày giá trị kinh doanh của kiểm thử cho ban lãnh đạo phi kỹ thuật, cách diễn đạt nào hiệu quả nhất?",
        en:"When presenting the business value of testing to non-technical executives, which framing is most effective?",
        ja:"非技術系の経営層にテストのビジネス価値を提示する際、最も効果的な表現はどれですか?" },
    options: [
      { vi:"Số ca kiểm thử tự động đã viết và độ bao phủ dòng lệnh", en:"Number of automated test cases written and line coverage", ja:"作成した自動テストケース数とラインカバレッジ" },
      { vi:"Danh sách các công cụ kiểm thử đang dùng", en:"A list of testing tools in use", ja:"使用中のテストツールのリスト" },
      { vi:"Chi phí lỗi tránh được, giảm rủi ro sản xuất và tác động tới doanh thu/uy tín", en:"Cost of defects avoided, reduced production risk and impact on revenue/reputation", ja:"回避された欠陥コスト、本番リスクの低減、収益・評判への影響" },
      { vi:"Số lượng khung kiểm thử được cấu hình", en:"Number of test frameworks configured", ja:"構成されたテストフレームワーク数" } ],
    answer: 2,
    exp: { vi:"Lãnh đạo phi kỹ thuật quan tâm tiền, rủi ro và uy tín. Trình bày chi phí lỗi tránh được, giảm rủi ro và tác động doanh thu gắn kiểm thử với ngôn ngữ kinh doanh. Các chỉ số kỹ thuật ít thuyết phục ở cấp này.",
          en:"Non-technical executives care about money, risk and reputation. Presenting cost of defects avoided, reduced risk and revenue impact ties testing to business language. Technical metrics are less persuasive at this level.",
          ja:"非技術系の経営層は金銭、リスク、評判を重視します。回避された欠陥コスト、リスク低減、収益への影響の提示がテストをビジネス言語に結びつけます。技術的指標はこのレベルでは説得力が劣ります。" } },

  { q: { vi:"Một nhóm kiểm thử phân tán qua 3 múi giờ gặp trễ phản hồi và hiểu lầm yêu cầu. Biện pháp quản lý nào ưu tiên cao nhất?",
        en:"A test team across 3 time zones suffers slow feedback and requirement misunderstandings. Which management action is highest priority?",
        ja:"3タイムゾーンに分散したテストチームがフィードバック遅延と要件誤解に悩む。最優先の管理策はどれですか?" },
    options: [
      { vi:"Yêu cầu tất cả làm việc theo giờ của trụ sở chính", en:"Require everyone to work headquarters hours", ja:"全員が本社の勤務時間に合わせる" },
      { vi:"Giảm số lượng tester ở các múi giờ xa", en:"Reduce the number of testers in remote time zones", ja:"遠隔タイムゾーンのテスター数を減らす" },
      { vi:"Chỉ dùng email và tránh mọi cuộc họp", en:"Use only email and avoid all meetings", ja:"メールのみ使い会議を避ける" },
      { vi:"Thiết lập giao tiếp rõ ràng, tài liệu chung, và khoảng thời gian trùng lặp cho họp đồng bộ", en:"Establish clear communication, shared documentation, and overlap hours for synchronous meetings", ja:"明確なコミュニケーション、共有文書、同期会議のための重複時間帯を確立する" } ],
    answer: 3,
    exp: { vi:"Với nhóm phân tán, kênh giao tiếp rõ ràng, tài liệu chung dễ truy cập và khung giờ trùng lặp để họp đồng bộ giúp giảm trễ phản hồi và hiểu lầm mà vẫn tôn trọng khác biệt múi giờ. Ép giờ hoặc cắt người gây rủi ro khác.",
          en:"For distributed teams, clear communication channels, accessible shared documentation and an overlap window for synchronous meetings reduce feedback delays and misunderstandings while respecting time-zone differences. Forcing hours or cutting staff creates other risks.",
          ja:"分散チームでは、明確なコミュニケーションチャネル、アクセス可能な共有文書、同期会議の重複時間帯が、タイムゾーン差を尊重しつつ遅延と誤解を減らします。勤務時間の強制や人員削減は別のリスクを生みます。" } },

  { q: { vi:"Khi thuê ngoài kiểm thử, rủi ro nào cần được kiểm soát bằng SLA và các chỉ số chất lượng rõ ràng?",
        en:"When outsourcing testing, which risk must be controlled by SLAs and clear quality metrics?",
        ja:"テストを外部委託する際、SLAと明確な品質指標で制御すべきリスクはどれですか?" },
    options: [
      { vi:"Nhà cung cấp có thể giao kết quả không nhất quán về chất lượng và độ bao phủ", en:"The vendor may deliver inconsistent quality and coverage", ja:"ベンダーが品質とカバレッジの一貫性を欠く成果を出す可能性" },
      { vi:"Nhà cung cấp luôn hiểu bối cảnh nghiệp vụ tốt hơn nội bộ", en:"The vendor always understands business context better than internal staff", ja:"ベンダーは常に社内より業務コンテキストを理解する" },
      { vi:"Thuê ngoài luôn rẻ hơn nên không cần đo lường", en:"Outsourcing is always cheaper so no measurement is needed", ja:"外部委託は常に安価なので測定不要である" },
      { vi:"Không có rủi ro nào cần kiểm soát khi đã ký hợp đồng", en:"No risk needs controlling once a contract is signed", ja:"契約締結後は制御すべきリスクはない" } ],
    answer: 0,
    exp: { vi:"Rủi ro chính khi thuê ngoài là chất lượng và độ bao phủ không nhất quán, khác biệt hiểu biết nghiệp vụ và giao tiếp. SLA cùng chỉ số chất lượng rõ ràng (DDP, rò lỗi, tiến độ) giúp giám sát và ràng buộc nhà cung cấp.",
          en:"The key outsourcing risk is inconsistent quality and coverage, plus gaps in business understanding and communication. SLAs with clear quality metrics (DDP, defect leakage, progress) enable monitoring and accountability.",
          ja:"外部委託の主なリスクは、品質とカバレッジの不一致、業務理解とコミュニケーションのギャップです。明確な品質指標（DDP、欠陥流出、進捗）を伴うSLAが監視と説明責任を可能にします。" } },

  { q: { vi:"Một trưởng nhóm phát hiện xung đột giữa hai tester về cách phân loại độ nghiêm trọng lỗi. Phong cách lãnh đạo phù hợp nhất là gì?",
        en:"A test lead finds a conflict between two testers over defect severity classification. What is the most appropriate leadership approach?",
        ja:"テストリードは欠陥重大度の分類を巡る2人のテスター間の対立を見つけた。最も適切なリーダーシップは何ですか?" },
    options: [
      { vi:"Áp đặt quyết định của mình để kết thúc nhanh", en:"Impose one's own decision to end it quickly", ja:"自分の決定を押し付けて素早く終わらせる" },
      { vi:"Tạo điều kiện thảo luận dựa trên tiêu chí phân loại đã thống nhất và tác động rủi ro để đạt đồng thuận có căn cứ", en:"Facilitate discussion based on agreed classification criteria and risk impact to reach an informed consensus", ja:"合意された分類基準とリスク影響に基づく議論を促し、根拠ある合意に導く" },
      { vi:"Bỏ qua vì đây là việc nhỏ", en:"Ignore it as a minor matter", ja:"些細な問題として無視する" },
      { vi:"Chuyển cả hai sang nhóm khác", en:"Move both testers to another team", ja:"両テスターを別チームへ異動させる" } ],
    answer: 1,
    exp: { vi:"Lãnh đạo hiệu quả xử lý xung đột bằng điều phối thảo luận dựa trên tiêu chí khách quan (định nghĩa severity, tác động rủi ro nghiệp vụ) để đạt đồng thuận có lý lẽ, đồng thời củng cố sự nhất quán và năng lực nhóm.",
          en:"Effective leadership resolves conflict by facilitating discussion grounded in objective criteria (severity definitions, business risk impact) to reach a reasoned consensus, reinforcing consistency and team capability.",
          ja:"効果的なリーダーシップは、客観的基準（重大度の定義、業務リスク影響）に基づく議論を促し、根拠ある合意に導くことで対立を解決し、一貫性とチーム能力を強化します。" } },

  { q: { vi:"Mô hình STEP nhấn mạnh điều gì khác biệt so với các mô hình dựa trên mức?",
        en:"What does the STEP model emphasize differently from level-based models?",
        ja:"STEPモデルはレベルベースのモデルと何が異なる点を強調しますか?" },
    options: [
      { vi:"Đạt mức trưởng thành cao nhất càng nhanh càng tốt", en:"Reaching the highest maturity level as fast as possible", ja:"できる限り速く最高成熟度レベルに到達すること" },
      { vi:"Chỉ kiểm thử sau khi mã hoàn tất hoàn toàn", en:"Testing only after code is fully complete", ja:"コード完成後のみテストする" },
      { vi:"Kiểm thử dựa trên yêu cầu, thực hiện song song với phát triển và bắt đầu sớm (testware trước code)", en:"Requirements-based testing in parallel with development, starting early (testware before code)", ja:"開発と並行して行う要件ベースのテストで、早期開始（コードより先にテストウェア）" },
      { vi:"Loại bỏ hoàn toàn tài liệu kiểm thử", en:"Eliminating all test documentation", ja:"すべてのテスト文書を廃止する" } ],
    answer: 2,
    exp: { vi:"STEP là mô hình phi mức, dựa trên yêu cầu, chủ trương kiểm thử song song và bắt đầu sớm — thiết kế testware có thể trước cả khi viết mã, giúp phát hiện lỗi yêu cầu sớm.",
          en:"STEP is a non-level, requirements-based model advocating parallel testing starting early - testware can be designed before code is written, catching requirement defects early.",
          ja:"STEPは非レベルの要件ベースモデルで、早期に並行してテストを行うことを推奨します。テストウェアはコード作成前に設計でき、要件欠陥を早期に検出します。" } },

  { q: { vi:"Trong đánh giá TMMi, bằng chứng nào là cần thiết để xác nhận một mục tiêu cụ thể đã đạt?",
        en:"In a TMMi assessment, what evidence is required to confirm a specific goal is achieved?",
        ja:"TMMiアセスメントで、特定目標の達成を確認するために必要な証拠は何ですか?" },
    options: [
      { vi:"Lời khẳng định miệng của quản lý dự án", en:"A verbal assertion from the project manager", ja:"プロジェクトマネージャーの口頭での主張" },
      { vi:"Chỉ cần công cụ kiểm thử đắt tiền được cài đặt", en:"Only that an expensive test tool is installed", ja:"高価なテストツールがインストールされていることのみ" },
      { vi:"Một bản trình chiếu marketing", en:"A marketing presentation", ja:"マーケティング用プレゼンテーション" },
      { vi:"Bằng chứng khách quan (tài liệu, hồ sơ, phỏng vấn) cho thấy các thực hành được thực hiện nhất quán", en:"Objective evidence (documents, records, interviews) showing practices are consistently performed", ja:"プラクティスが一貫して実施されていることを示す客観的証拠（文書、記録、面談）" } ],
    answer: 3,
    exp: { vi:"Đánh giá TMMi dựa trên bằng chứng khách quan: tài liệu, hồ sơ thực thi và phỏng vấn để xác nhận các thực hành cụ thể được thực hiện nhất quán và thể chế hóa, chứ không dựa vào lời nói suông.",
          en:"TMMi assessment relies on objective evidence: artefacts, execution records and interviews confirming specific practices are consistently performed and institutionalized, not on mere assertions.",
          ja:"TMMiアセスメントは客観的証拠（成果物、実行記録、面談）に依拠し、特定プラクティスが一貫して実施・制度化されていることを確認します。単なる主張ではありません。" } },

  { q: { vi:"Phương pháp GQM (Goal-Question-Metric) được dùng để làm gì trong cải tiến quy trình kiểm thử?",
        en:"What is the GQM method used for in test process improvement?",
        ja:"GQM法はテストプロセス改善で何に使われますか?" },
    options: [
      { vi:"Rút ra các chỉ số đo lường một cách có hệ thống từ mục tiêu qua các câu hỏi trung gian", en:"Systematically deriving metrics from goals via intermediate questions", ja:"目標から中間的な質問を経てメトリクスを体系的に導出すること" },
      { vi:"Chọn công cụ kiểm thử tự động rẻ nhất", en:"Selecting the cheapest automation tool", ja:"最も安価な自動化ツールの選定" },
      { vi:"Xếp hạng độ nghiêm trọng của lỗi", en:"Ranking defect severity", ja:"欠陥重大度のランク付け" },
      { vi:"Lập lịch chạy kiểm thử hồi quy", en:"Scheduling regression test runs", ja:"回帰テスト実行のスケジューリング" } ],
    answer: 0,
    exp: { vi:"GQM là cách tiếp cận từ trên xuống: bắt đầu từ mục tiêu (Goal), đặt câu hỏi (Question) để đánh giá mục tiêu, rồi xác định các chỉ số (Metric) trả lời câu hỏi. Điều này đảm bảo mỗi chỉ số có mục đích rõ ràng.",
          en:"GQM is a top-down approach: start from a Goal, pose Questions to assess it, then define Metrics that answer the questions. This ensures every metric has a clear purpose.",
          ja:"GQMはトップダウンのアプローチです。ゴールから始め、それを評価する質問を立て、質問に答えるメトリクスを定義します。これにより各メトリクスに明確な目的が生まれます。" } },

  { q: { vi:"Khi ước lượng nỗ lực kiểm thử cho dự án lớn dùng phán đoán chuyên gia, kỹ thuật nào giúp giảm thiên lệch cá nhân?",
        en:"When estimating test effort for a large project using expert judgment, which technique reduces individual bias?",
        ja:"大規模プロジェクトのテスト工数を専門家の判断で見積もる際、個人の偏りを減らす技法はどれですか?" },
    options: [
      { vi:"Chỉ hỏi một chuyên gia giàu kinh nghiệm nhất", en:"Ask only the single most experienced expert", ja:"最も経験豊富な専門家1人にのみ尋ねる" },
      { vi:"Kỹ thuật Wideband Delphi — nhiều chuyên gia ước lượng độc lập rồi hội tụ qua thảo luận", en:"Wideband Delphi - multiple experts estimate independently then converge through discussion", ja:"ワイドバンドデルファイ法—複数の専門家が独立して見積もり、議論を通じて収束する" },
      { vi:"Nhân đôi ước lượng của quản lý", en:"Double the manager's estimate", ja:"マネージャーの見積もりを2倍にする" },
      { vi:"Dùng con số của dự án hoàn toàn khác không hiệu chỉnh", en:"Use figures from a completely different project without adjustment", ja:"全く異なるプロジェクトの数値を調整せずに使う" } ],
    answer: 1,
    exp: { vi:"Wideband Delphi để nhiều chuyên gia ước lượng độc lập rồi thảo luận và hội tụ qua nhiều vòng, giúp giảm thiên lệch cá nhân và tận dụng kiến thức tập thể. Dựa vào một người hay con số không hiệu chỉnh dễ sai lệch.",
          en:"Wideband Delphi has multiple experts estimate independently, then discuss and converge over rounds, reducing individual bias and leveraging collective knowledge. Relying on one person or uncalibrated figures is error-prone.",
          ja:"ワイドバンドデルファイ法では、複数の専門家が独立して見積もり、複数ラウンドで議論・収束します。これにより個人の偏りが減り、集団知が活用されます。1人や未調整の数値への依存は誤りを招きます。" } },

  { q: { vi:"Tổ chức muốn so sánh hiệu quả quy trình kiểm thử của mình với các tổ chức khác trong ngành. Hoạt động này gọi là gì?",
        en:"An organization wants to compare its test process effectiveness against others in the industry. What is this called?",
        ja:"組織は自社のテストプロセスの有効性を業界の他社と比較したい。この活動は何と呼ばれますか?" },
    options: [
      { vi:"Refactoring", en:"Refactoring", ja:"リファクタリング" },
      { vi:"Prototyping", en:"Prototyping", ja:"プロトタイピング" },
      { vi:"Benchmarking", en:"Benchmarking", ja:"ベンチマーキング" },
      { vi:"Debugging", en:"Debugging", ja:"デバッグ" } ],
    answer: 2,
    exp: { vi:"Benchmarking là so sánh hiệu suất/quy trình của tổ chức với các chuẩn ngành hoặc tổ chức khác để nhận diện khoảng cách và cơ hội cải tiến. Đây là công cụ hữu ích trong cải tiến quy trình kiểm thử.",
          en:"Benchmarking compares an organization's performance/processes against industry standards or peers to identify gaps and improvement opportunities. It is a useful tool in test process improvement.",
          ja:"ベンチマーキングは、組織のパフォーマンスやプロセスを業界標準や同業他社と比較し、ギャップと改善機会を特定します。テストプロセス改善で有用なツールです。" } },

  { q: { vi:"Một chương trình cải tiến vấp phải sự kháng cự từ nhân viên. Yếu tố con người nào cần được ưu tiên xử lý trước tiên?",
        en:"An improvement program faces staff resistance. Which human factor should be addressed first?",
        ja:"改善プログラムがスタッフの抵抗に直面する。まず対処すべき人的要因はどれですか?" },
    options: [
      { vi:"Mua thêm giấy phép công cụ", en:"Buying more tool licenses", ja:"ツールライセンスの追加購入" },
      { vi:"Cắt giảm nhân sự phản đối", en:"Cutting staff who object", ja:"反対するスタッフを削減する" },
      { vi:"Bỏ qua và tiếp tục ép buộc thay đổi", en:"Ignore it and keep forcing the change", ja:"無視して変更を強制し続ける" },
      { vi:"Truyền đạt tầm nhìn, giải thích lợi ích và lôi kéo nhân viên tham gia để tạo cảm giác sở hữu", en:"Communicate the vision, explain benefits and involve staff to build ownership", ja:"ビジョンを伝え、便益を説明し、スタッフを巻き込んでオーナーシップを築く" } ],
    answer: 3,
    exp: { vi:"Kháng cự thay đổi là yếu tố con người then chốt. Quản lý thay đổi hiệu quả cần truyền đạt tầm nhìn, làm rõ lợi ích, và lôi kéo nhân viên tham gia để tạo cảm giác sở hữu, thay vì ép buộc hay trừng phạt.",
          en:"Resistance to change is a key human factor. Effective change management requires communicating the vision, clarifying benefits and involving staff to build ownership, rather than coercion or punishment.",
          ja:"変化への抵抗は重要な人的要因です。効果的な変更管理は、強制や罰ではなく、ビジョンの伝達、便益の明確化、スタッフの巻き込みによるオーナーシップの構築を必要とします。" } },

  { q: { vi:"CTP (Critical Testing Processes) xác định các quy trình then chốt và đánh giá chúng dựa trên yếu tố nào?",
        en:"CTP identifies critical processes and assesses them based on what?",
        ja:"CTPは重要プロセスを特定し、何に基づいて評価しますか?" },
    options: [
      { vi:"Các thuộc tính định tính và định lượng, điểm mạnh/yếu của từng quy trình then chốt trong bối cảnh cụ thể", en:"Qualitative and quantitative attributes, strengths/weaknesses of each critical process in context", ja:"各重要プロセスの文脈における定性的・定量的属性、強み/弱み" },
      { vi:"Số dòng mã đã kiểm thử", en:"Lines of code tested", ja:"テストされたコード行数" },
      { vi:"Chỉ mức trưởng thành theo bậc", en:"Only staged maturity levels", ja:"段階的成熟度レベルのみ" },
      { vi:"Ngân sách của phòng kiểm thử", en:"The test department budget", ja:"テスト部門の予算" } ],
    answer: 0,
    exp: { vi:"CTP là mô hình dựa trên nội dung, phi mức, xác định các quy trình then chốt và đánh giá điểm mạnh/yếu định tính lẫn định lượng của chúng trong bối cảnh tổ chức, giúp ưu tiên cải tiến linh hoạt.",
          en:"CTP is a content-based, non-level model that identifies critical processes and assesses their qualitative and quantitative strengths/weaknesses in the organizational context, enabling flexible improvement prioritization.",
          ja:"CTPはコンテンツベースの非レベルモデルで、重要プロセスを特定し、組織の文脈における定性的・定量的な強み/弱みを評価し、柔軟な改善の優先順位付けを可能にします。" } },

  { q: { vi:"Chỉ số 'defect leakage' giữa các giai đoạn kiểm thử cho biết điều gì?",
        en:"What does the 'defect leakage' metric between test phases indicate?",
        ja:"テストフェーズ間の「欠陥流出」指標は何を示しますか?" },
    options: [
      { vi:"Số công cụ kiểm thử đang dùng", en:"Number of test tools in use", ja:"使用中のテストツール数" },
      { vi:"Tỷ lệ lỗi lẽ ra phải bắt được ở giai đoạn trước nhưng lại lọt sang giai đoạn sau", en:"The proportion of defects that should have been caught earlier but escaped to a later phase", ja:"前フェーズで検出すべきだったが後フェーズへ漏れた欠陥の割合" },
      { vi:"Tổng số ca kiểm thử tự động", en:"Total automated test cases", ja:"自動テストケースの総数" },
      { vi:"Chi phí giấy phép phần mềm", en:"Software license cost", ja:"ソフトウェアライセンス費用" } ],
    answer: 1,
    exp: { vi:"Defect leakage đo tỷ lệ lỗi lọt qua một giai đoạn mà lẽ ra phải phát hiện tại đó, giúp đánh giá hiệu quả từng mức kiểm thử và định vị nơi cần cải tiến. Rò rỉ cao ở giai đoạn sớm báo hiệu điểm yếu.",
          en:"Defect leakage measures the proportion of defects escaping a phase where they should have been found, helping assess each phase's effectiveness and locate where improvement is needed. High leakage from early phases signals weakness.",
          ja:"欠陥流出は、あるフェーズで検出すべきだった欠陥がそこを通過した割合を測定し、各フェーズの有効性評価と改善が必要な箇所の特定に役立ちます。早期フェーズからの高い流出は弱点を示します。" } },

  { q: { vi:"Một tổ chức đạt TMMi mức 2 muốn tiến lên mức 3. Ưu tiên hành động nào phù hợp với mục tiêu này?",
        en:"An organization at TMMi Level 2 aims to reach Level 3. Which action priority aligns with this goal?",
        ja:"TMMiレベル2の組織がレベル3を目指す。この目標に沿った行動の優先順位はどれですか?" },
    options: [
      { vi:"Tập trung vào tối ưu hóa quy trình bằng phòng ngừa lỗi (mức 5)", en:"Focus on process optimization via defect prevention (Level 5)", ja:"欠陥予防によるプロセス最適化（レベル5）に集中する" },
      { vi:"Triển khai đo lường định lượng nâng cao (mức 4) trước", en:"Deploy advanced quantitative measurement (Level 4) first", ja:"高度な定量的測定（レベル4）を先に導入する" },
      { vi:"Thiết lập quy trình kiểm thử chuẩn ở cấp tổ chức và tích hợp kiểm thử vào toàn bộ vòng đời", en:"Establish organization-level standard test processes and integrate testing across the whole lifecycle", ja:"組織レベルの標準テストプロセスを確立し、ライフサイクル全体にテストを統合する" },
      { vi:"Chỉ cần lập kế hoạch kiểm thử cho từng dự án riêng lẻ", en:"Just plan testing per individual project", ja:"個別プロジェクトごとにテスト計画を立てるだけ" } ],
    answer: 2,
    exp: { vi:"Từ mức 2 (Managed, quy trình theo dự án) lên mức 3 (Defined), trọng tâm là chuẩn hóa quy trình kiểm thử ở cấp tổ chức và tích hợp kiểm thử vào toàn vòng đời. Mức 4 và 5 đến sau; lập kế hoạch theo dự án đã thuộc mức 2.",
          en:"Moving from Level 2 (Managed, project-level) to Level 3 (Defined) centers on standardizing test processes organization-wide and integrating testing across the lifecycle. Levels 4 and 5 come later; per-project planning is already Level 2.",
          ja:"レベル2（管理された、プロジェクトレベル）からレベル3（定義された）へは、テストプロセスの組織全体での標準化とライフサイクル全体への統合が中心です。レベル4と5は後で、プロジェクトごとの計画は既にレベル2です。" } },

  { q: { vi:"Khi lựa chọn giữa mô hình cải tiến dựa trên tiến trình và dựa trên phân tích, yếu tố quyết định chính là gì?",
        en:"When choosing between a process-reference model and an analytical model, what is the main deciding factor?",
        ja:"プロセス参照モデルと分析型モデルのどちらを選ぶか決める主な要因は何ですか?" },
    options: [
      { vi:"Màu sắc logo của mô hình", en:"The model's logo color", ja:"モデルのロゴの色" },
      { vi:"Số trang của tài liệu mô hình", en:"Number of pages in the model document", ja:"モデル文書のページ数" },
      { vi:"Ngôn ngữ lập trình dự án dùng", en:"The project's programming language", ja:"プロジェクトのプログラミング言語" },
      { vi:"Mục tiêu, bối cảnh tổ chức, nguồn lực và nhu cầu đánh giá bên ngoài hay cải tiến nội bộ nhanh", en:"Goals, organizational context, resources, and need for external certification versus fast internal improvement", ja:"目標、組織の文脈、リソース、外部認証の必要性 対 迅速な内部改善" } ],
    answer: 3,
    exp: { vi:"Việc chọn mô hình phụ thuộc mục tiêu, bối cảnh, nguồn lực và nhu cầu: nếu cần chứng nhận hay so sánh chuẩn ngành thì mô hình tiến trình (TMMi/TPI Next); nếu cần cải tiến nhanh, tập trung vấn đề cụ thể thì mô hình phân tích.",
          en:"Model choice depends on goals, context, resources and needs: for certification/industry comparison use process-reference models (TMMi/TPI Next); for fast, problem-focused improvement use analytical models.",
          ja:"モデル選択は目標、文脈、リソース、ニーズに依存します。認証や業界比較にはプロセス参照モデル（TMMi/TPI Next）、迅速で問題重視の改善には分析型モデルを使います。" } },

  { q: { vi:"Governance kiểm thử ở cấp tổ chức chủ yếu đảm bảo điều gì?",
        en:"Test governance at the organizational level primarily ensures what?",
        ja:"組織レベルのテストガバナンスは主に何を保証しますか?" },
    options: [
      { vi:"Hoạt động kiểm thử nhất quán với chính sách, tuân thủ quy định và gắn với mục tiêu chiến lược của tổ chức", en:"Testing aligns with policy, complies with regulations, and supports organizational strategic objectives", ja:"テストがポリシーに沿い、規制に準拠し、組織の戦略目標を支えること" },
      { vi:"Mọi tester dùng cùng một bàn phím", en:"Every tester uses the same keyboard", ja:"全テスターが同じキーボードを使う" },
      { vi:"Số ca kiểm thử luôn tăng mỗi tháng", en:"Test case count always grows monthly", ja:"テストケース数が毎月必ず増える" },
      { vi:"Chỉ dùng công cụ mã nguồn mở", en:"Only open-source tools are used", ja:"オープンソースツールのみ使用する" } ],
    answer: 0,
    exp: { vi:"Governance kiểm thử đảm bảo hoạt động kiểm thử nhất quán với chính sách và chiến lược tổ chức, tuân thủ quy định, có trách nhiệm giải trình và giám sát rõ ràng — kết nối kiểm thử với mục tiêu kinh doanh và quản trị doanh nghiệp.",
          en:"Test governance ensures testing aligns with organizational policy and strategy, complies with regulations, and provides clear accountability and oversight - connecting testing to business objectives and corporate governance.",
          ja:"テストガバナンスは、テストが組織のポリシーと戦略に沿い、規制に準拠し、明確な説明責任と監督を提供することを保証し、テストをビジネス目標と企業統治に結びつけます。" } },

  { q: { vi:"Trong quản lý nhóm phân tán, 'follow-the-sun' mang lại lợi ích nào và đòi hỏi điều kiện gì?",
        en:"In distributed team management, what benefit does 'follow-the-sun' provide and what does it require?",
        ja:"分散チーム管理で「フォロー・ザ・サン」はどんな利点をもたらし、何を必要としますか?" },
    options: [
      { vi:"Giảm chi phí giấy phép; đòi hỏi cùng ngôn ngữ lập trình", en:"Reduces license cost; requires the same programming language", ja:"ライセンス費用削減；同じプログラミング言語を要求する" },
      { vi:"Rút ngắn thời gian chu kỳ nhờ làm việc gần như liên tục 24h; đòi hỏi bàn giao rõ ràng và tài liệu tốt giữa các địa điểm", en:"Shortens cycle time via near-24h continuous work; requires clear handovers and good documentation across sites", ja:"ほぼ24時間の連続作業でサイクル時間を短縮；拠点間の明確な引き継ぎと良い文書化を要求する" },
      { vi:"Loại bỏ nhu cầu quản lý; không đòi hỏi gì", en:"Eliminates the need for management; requires nothing", ja:"管理の必要をなくし、何も要求しない" },
      { vi:"Tăng lỗi và không có lợi ích nào", en:"Increases defects with no benefit", ja:"欠陥を増やし利点はない" } ],
    answer: 1,
    exp: { vi:"Follow-the-sun tận dụng chênh lệch múi giờ để công việc chạy gần như liên tục, rút ngắn thời gian chu kỳ. Nhưng nó phụ thuộc mạnh vào bàn giao rõ ràng, tài liệu chất lượng và công cụ cộng tác để tránh mất thông tin giữa các ca.",
          en:"Follow-the-sun leverages time-zone differences so work runs almost continuously, shortening cycle time. But it depends heavily on clear handovers, quality documentation and collaboration tools to avoid information loss between shifts.",
          ja:"フォロー・ザ・サンはタイムゾーン差を活用し作業をほぼ連続させ、サイクル時間を短縮します。ただしシフト間の情報損失を防ぐため、明確な引き継ぎ、質の高い文書、コラボツールに大きく依存します。" } },

  { q: { vi:"Một quản lý cần chứng minh giá trị của việc tự động hóa hồi quy. Chỉ số kinh doanh nào thuyết phục nhất?",
        en:"A test manager must justify the value of regression automation. Which business metric is most convincing?",
        ja:"テストマネージャーは回帰自動化の価値を正当化する。最も説得力のあるビジネス指標はどれですか?" },
    options: [
      { vi:"Số dòng mã của bộ kịch bản tự động", en:"Lines of code in the automation suite", ja:"自動化スイートのコード行数" },
      { vi:"Số lần script thất bại do lỗi môi trường", en:"Number of script failures due to environment issues", ja:"環境問題によるスクリプト失敗回数" },
      { vi:"Thời gian hồi quy rút ngắn cho phép phát hành nhanh hơn cùng chi phí lỗi hồi quy giảm, quy ra tiền và tốc độ ra thị trường", en:"Reduced regression time enabling faster releases plus lower regression-defect cost, expressed in money and time-to-market", ja:"回帰時間短縮による高速リリースと回帰欠陥コストの低減を、金額と市場投入時間で表す" },
      { vi:"Tổng số commit trong kho mã", en:"Total commits in the code repository", ja:"コードリポジトリの総コミット数" } ],
    answer: 2,
    exp: { vi:"Giá trị tự động hóa được chứng minh tốt nhất bằng ngôn ngữ kinh doanh: thời gian hồi quy giảm cho phép phát hành nhanh hơn, chi phí lỗi hồi quy tránh được, và giải phóng nhân lực cho kiểm thử khám phá — tất cả quy ra tiền và tốc độ.",
          en:"Automation value is best shown in business language: reduced regression time enabling faster time-to-market, avoided regression-defect cost, and freeing staff for exploratory testing - all expressed in money and speed.",
          ja:"自動化の価値はビジネス言語で示すのが最善です。回帰時間短縮による市場投入の高速化、回避された回帰欠陥コスト、探索的テストへの人員解放を、金額と速度で表します。" } },

  { q: { vi:"Trong TPI Next, các 'cluster' được dùng để làm gì?",
        en:"In TPI Next, what are 'clusters' used for?",
        ja:"TPI Nextで「クラスター」は何に使われますか?" },
    options: [
      { vi:"Nhóm các máy chủ kiểm thử theo vị trí", en:"Grouping test servers by location", ja:"テストサーバーを場所別にグループ化する" },
      { vi:"Phân loại lỗi theo độ nghiêm trọng", en:"Classifying defects by severity", ja:"欠陥を重大度で分類する" },
      { vi:"Chọn ngôn ngữ lập trình", en:"Choosing a programming language", ja:"プログラミング言語を選ぶ" },
      { vi:"Nhóm các mức của khu vực chính để đưa ra lộ trình cải tiến theo bước và thứ tự đạt các mức trưởng thành", en:"Grouping key-area levels to give a step-by-step improvement roadmap and sequence for reaching maturity", ja:"キーエリアのレベルをグループ化し、段階的な改善ロードマップと成熟度到達の順序を示す" } ],
    answer: 3,
    exp: { vi:"Trong TPI Next, cluster nhóm các mức của nhiều khu vực chính lại thành các bước cải tiến, tạo lộ trình có thứ tự để tổ chức nâng dần độ trưởng thành một cách cân đối giữa các khu vực.",
          en:"In TPI Next, clusters group levels across key areas into improvement steps, forming an ordered roadmap so the organization raises maturity in a balanced way across areas.",
          ja:"TPI Nextでは、クラスターは複数のキーエリアにまたがるレベルを改善ステップにグループ化し、組織がエリア間でバランスよく成熟度を高める順序付きロードマップを形成します。" } },

  { q: { vi:"Một tổ chức thấy nhiều lỗi lặp lại có cùng nguyên nhân. Kỹ thuật cải tiến nào nên áp dụng để ngăn tái diễn?",
        en:"An organization sees many recurring defects sharing a common cause. Which technique should be applied to prevent recurrence?",
        ja:"組織は共通原因を持つ再発欠陥を多く見る。再発防止に適用すべき技法はどれですか?" },
    options: [
      { vi:"Phân tích nguyên nhân gốc để loại bỏ nguồn gốc và cải tiến quy trình thượng nguồn", en:"Root cause analysis to eliminate the source and improve upstream processes", ja:"根本原因分析で原因を除去し、上流プロセスを改善する" },
      { vi:"Tăng số ca kiểm thử một cách ngẫu nhiên", en:"Randomly increase the number of test cases", ja:"テストケース数をランダムに増やす" },
      { vi:"Chỉ ghi nhận lỗi mà không phân tích", en:"Just log defects without analysis", ja:"分析せず欠陥を記録するだけ" },
      { vi:"Giảm phạm vi kiểm thử để thấy ít lỗi hơn", en:"Reduce test scope to see fewer defects", ja:"テスト範囲を減らして欠陥を減らす" } ],
    answer: 0,
    exp: { vi:"Phân tích nguyên nhân gốc xác định nguồn thực sự của các lỗi lặp lại (thiếu sót yêu cầu, thiếu chuẩn code) và cải tiến quy trình thượng nguồn để phòng ngừa, thay vì chỉ sửa triệu chứng. Đây là nền tảng của mức trưởng thành cao.",
          en:"Root cause analysis identifies the true source of recurring defects (requirement gaps, missing code standards) and improves upstream processes to prevent them, rather than fixing symptoms. It underpins high maturity.",
          ja:"根本原因分析は再発欠陥の真の原因（要件の欠落、コード標準の不在など）を特定し、症状ではなく上流プロセスを改善して予防します。これは高い成熟度の基盤です。" } },

  { q: { vi:"Khi phát triển kỹ năng cho nhóm kiểm thử, mô hình năng lực hỗ trợ quản lý ra sao?",
        en:"When developing test team skills, how does a competency model help management?",
        ja:"テストチームのスキル育成で、コンピテンシーモデルは管理をどう支援しますか?" },
    options: [
      { vi:"Nó tự động viết ca kiểm thử", en:"It automatically writes test cases", ja:"自動的にテストケースを書く" },
      { vi:"Nó xác định năng lực cần thiết, đánh giá khoảng cách kỹ năng và định hướng đào tạo, tuyển dụng, phân công phù hợp", en:"It defines required competencies, assesses skill gaps and guides training, recruitment and appropriate assignment", ja:"必要なコンピテンシーを定義し、スキルギャップを評価し、訓練・採用・適切な配置を導く" },
      { vi:"Nó thay thế nhu cầu quản lý con người", en:"It replaces the need to manage people", ja:"人を管理する必要をなくす" },
      { vi:"Nó chỉ hữu ích cho bộ phận marketing", en:"It is only useful for marketing", ja:"マーケティングにのみ有用である" } ],
    answer: 1,
    exp: { vi:"Mô hình năng lực định nghĩa các kỹ năng cần cho vai trò kiểm thử, cho phép đánh giá khoảng cách của cá nhân và nhóm, từ đó lập kế hoạch đào tạo, tuyển dụng và phân công phù hợp — một công cụ quản lý con người quan trọng.",
          en:"A competency model defines skills needed for testing roles, enabling assessment of individual and team gaps, then planning training, recruitment and suitable assignments - an important people-management tool.",
          ja:"コンピテンシーモデルはテスト職に必要なスキルを定義し、個人とチームのギャップ評価を可能にし、訓練・採用・適切な配置の計画に役立つ重要な人材管理ツールです。" } },

  { q: { vi:"Một dự án dùng Agile ở quy mô lớn. Cách tiếp cận cải tiến quy trình kiểm thử nào phù hợp nhất với văn hóa lặp liên tục?",
        en:"A project uses Agile at scale. Which test process improvement approach best fits a culture of continuous iteration?",
        ja:"プロジェクトは大規模アジャイルを使う。継続的反復の文化に最も適したテストプロセス改善アプローチはどれですか?" },
    options: [
      { vi:"Đánh giá TMMi đầy đủ một lần rồi không xem lại", en:"A one-off full TMMi assessment never revisited", ja:"一度きりの完全TMMiアセスメントで見直さない" },
      { vi:"Ngừng mọi cải tiến vì Agile không cần quy trình", en:"Stop all improvement because Agile needs no process", ja:"アジャイルはプロセス不要なので改善を止める" },
      { vi:"Cải tiến liên tục dựa trên retrospective, đo lường ngắn hạn và điều chỉnh nhanh, có thể kết hợp mục tiêu từ mô hình trưởng thành", en:"Continuous improvement via retrospectives, short-cycle metrics and rapid adjustment, optionally guided by maturity-model goals", ja:"レトロスペクティブ、短サイクル測定、迅速な調整による継続的改善（成熟度モデルの目標で補完可能）" },
      { vi:"Chỉ dựa vào tài liệu quy trình cứng nhắc", en:"Rely only on rigid process documentation", ja:"硬直的なプロセス文書のみに依存する" } ],
    answer: 2,
    exp: { vi:"Trong Agile quy mô lớn, cải tiến liên tục qua retrospective, đo lường ngắn hạn và điều chỉnh nhanh khớp với văn hóa lặp. Mô hình trưởng thành vẫn có thể cung cấp mục tiêu định hướng, nhưng cần áp dụng linh hoạt, tránh đánh giá nặng nề một lần.",
          en:"In Agile at scale, continuous improvement via retrospectives, short-cycle metrics and rapid adjustment fits the iterative culture. Maturity models can still provide guiding goals but must be applied flexibly, avoiding heavy one-off assessments.",
          ja:"大規模アジャイルでは、レトロスペクティブ、短サイクル測定、迅速な調整による継続的改善が反復文化に適します。成熟度モデルは指針となる目標を提供できますが、重い一度きりのアセスメントを避け柔軟に適用すべきです。" } },

  { q: { vi:"Khi xây dựng business case cho một chương trình cải tiến, thành phần nào là cần thiết ngoài chi phí và lợi ích?",
        en:"When building a business case for an improvement program, which component is essential besides costs and benefits?",
        ja:"改善プログラムのビジネスケースで、コストと便益以外に不可欠な要素はどれですか?" },
    options: [
      { vi:"Danh sách sở thích cá nhân của quản lý", en:"A list of the manager's personal preferences", ja:"マネージャーの個人的な好みのリスト" },
      { vi:"Màu sắc slide trình bày", en:"The slide deck's colors", ja:"スライドの色" },
      { vi:"Số lượng cuộc họp đã tổ chức", en:"The number of meetings held", ja:"開催した会議の数" },
      { vi:"Rủi ro, giả định, khung thời gian và các chỉ số đo lường thành công", en:"Risks, assumptions, timeframe and success metrics", ja:"リスク、前提、期間、成功指標" } ],
    answer: 3,
    exp: { vi:"Một business case vững chắc ngoài chi phí/lợi ích còn phải nêu rõ rủi ro, giả định, khung thời gian và tiêu chí đo lường thành công — để lãnh đạo ra quyết định có căn cứ và theo dõi được kết quả sau này.",
          en:"A solid business case, beyond costs/benefits, must state risks, assumptions, timeframe and success metrics - so management can decide informedly and later track outcomes.",
          ja:"堅実なビジネスケースは、コストと便益に加え、リスク、前提、期間、成功指標を明示する必要があります。これにより経営層が根拠ある意思決定を行い、後で成果を追跡できます。" } },

  { q: { vi:"Chỉ số 'cost of quality' được chia thành các loại nào giúp phân tích đầu tư kiểm thử?",
        en:"Into which categories is 'cost of quality' divided to help analyze testing investment?",
        ja:"テスト投資分析に役立つ「品質コスト」はどのカテゴリーに分けられますか?" },
    options: [
      { vi:"Chi phí phòng ngừa, chi phí đánh giá, chi phí thất bại nội bộ và chi phí thất bại bên ngoài", en:"Prevention, appraisal, internal failure and external failure costs", ja:"予防コスト、評価コスト、内部失敗コスト、外部失敗コスト" },
      { vi:"Chi phí phần cứng và phần mềm", en:"Hardware and software costs", ja:"ハードウェアとソフトウェアのコスト" },
      { vi:"Chi phí lương và chi phí văn phòng", en:"Salary and office costs", ja:"給与と事務所コスト" },
      { vi:"Chi phí marketing và bán hàng", en:"Marketing and sales costs", ja:"マーケティングと営業コスト" } ],
    answer: 0,
    exp: { vi:"Cost of Quality gồm chi phí phù hợp (phòng ngừa cộng đánh giá) và chi phí không phù hợp (thất bại nội bộ cộng thất bại bên ngoài). Phân tích này giúp lập luận rằng đầu tư phòng ngừa/đánh giá sớm rẻ hơn nhiều so với thất bại bên ngoài.",
          en:"Cost of Quality comprises conformance costs (prevention plus appraisal) and non-conformance costs (internal plus external failure). This analysis argues that early prevention/appraisal investment is far cheaper than external failures.",
          ja:"品質コストは適合コスト（予防＋評価）と不適合コスト（内部失敗＋外部失敗）から成ります。この分析は、早期の予防・評価投資が外部失敗よりはるかに安いことを論証します。" } },

  { q: { vi:"Một trưởng nhóm nhận thấy một tester giỏi kỹ thuật nhưng thường đối đầu với dev, gây căng thẳng. Hành động phát triển con người phù hợp nhất là gì?",
        en:"A lead notices a technically strong tester who frequently clashes with developers, creating tension. What is the most appropriate people-development action?",
        ja:"リードは技術的に優れているが開発者と頻繁に衝突するテスターに気づく。最も適切な人材育成策は何ですか?" },
    options: [
      { vi:"Sa thải ngay để loại bỏ căng thẳng", en:"Dismiss them immediately to remove tension", ja:"緊張をなくすため即座に解雇する" },
      { vi:"Cung cấp phản hồi, huấn luyện kỹ năng giao tiếp và cộng tác, gắn với mục tiêu phát triển cá nhân", en:"Provide feedback, coach communication and collaboration skills, tied to a personal development plan", ja:"フィードバックを提供し、コミュニケーションと協働のスキルをコーチし、個人育成計画に結びつける" },
      { vi:"Cấm tester đó nói chuyện với dev", en:"Ban that tester from talking to developers", ja:"そのテスターが開発者と話すことを禁止する" },
      { vi:"Bỏ qua vì kỹ năng kỹ thuật là đủ", en:"Ignore it since technical skill is enough", ja:"技術力があれば十分なので無視する" } ],
    answer: 1,
    exp: { vi:"Kỹ năng mềm quan trọng ngang kỹ thuật. Lãnh đạo tốt cung cấp phản hồi mang tính xây dựng và coaching, gắn với kế hoạch phát triển cá nhân, giúp tester phát huy điểm mạnh kỹ thuật mà không gây xung đột.",
          en:"Soft skills matter as much as technical ability. Good leadership gives constructive feedback and coaching tied to a personal development plan, helping the tester leverage technical strength without conflict.",
          ja:"ソフトスキルは技術力と同じくらい重要です。優れたリーダーシップは、個人育成計画に結びついた建設的なフィードバックとコーチングを提供し、テスターが衝突なく技術的強みを活かせるよう支援します。" } },

  { q: { vi:"Trong quản lý test phân tán, mô hình 'captive center' khác 'outsourcing' ở điểm nào?",
        en:"In distributed test management, how does a 'captive center' differ from 'outsourcing'?",
        ja:"分散テスト管理で「キャプティブセンター」は「アウトソーシング」とどう異なりますか?" },
    options: [
      { vi:"Không có khác biệt nào", en:"There is no difference", ja:"違いはない" },
      { vi:"Captive center luôn ở trong nước", en:"A captive center is always onshore", ja:"キャプティブセンターは常に国内にある" },
      { vi:"Captive center thuộc sở hữu và kiểm soát của chính công ty, trong khi outsourcing giao cho nhà cung cấp bên thứ ba", en:"A captive center is owned and controlled by the company itself, while outsourcing delegates to a third-party vendor", ja:"キャプティブセンターは自社が所有・管理するが、アウトソーシングは第三者ベンダーに委託する" },
      { vi:"Outsourcing luôn đắt hơn captive center", en:"Outsourcing is always more expensive than a captive center", ja:"アウトソーシングは常にキャプティブセンターより高い" } ],
    answer: 2,
    exp: { vi:"Captive center là đơn vị do chính công ty sở hữu và vận hành (thường ở nước chi phí thấp), giữ kiểm soát trực tiếp về nhân sự, quy trình và tri thức. Outsourcing giao việc cho nhà cung cấp bên ngoài, đánh đổi kiểm soát lấy linh hoạt/chi phí.",
          en:"A captive center is owned and run by the company itself (often in a low-cost country), retaining direct control of staff, process and knowledge. Outsourcing delegates work to an external vendor, trading control for flexibility/cost.",
          ja:"キャプティブセンターは自社が所有・運営する組織（多くは低コスト国）で、人員・プロセス・知識を直接管理します。アウトソーシングは外部ベンダーに委託し、管理と引き換えに柔軟性・コストを得ます。" } },

  { q: { vi:"Khi một chương trình cải tiến chọn các cải tiến để triển khai trước, tiêu chí ưu tiên hợp lý nhất là gì?",
        en:"When an improvement program selects which improvements to implement first, what is the most sensible prioritization criterion?",
        ja:"改善プログラムが最初に実施する改善を選ぶ際、最も合理的な優先順位付け基準は何ですか?" },
    options: [
      { vi:"Cải tiến nào có tên hấp dẫn nhất", en:"Whichever improvement has the catchiest name", ja:"最も魅力的な名前の改善" },
      { vi:"Cải tiến đắt nhất để thể hiện cam kết", en:"The most expensive improvement to show commitment", ja:"コミットメントを示すため最も高価な改善" },
      { vi:"Cải tiến mà chỉ một người ủng hộ", en:"The improvement only one person supports", ja:"1人だけが支持する改善" },
      { vi:"Tác động kinh doanh cao và khả thi (nỗ lực/rủi ro thấp) — cân bằng giá trị và tính khả thi", en:"High business impact and feasibility (low effort/risk) - balancing value and feasibility", ja:"高いビジネスインパクトと実現可能性（低い工数・リスク）—価値と実現性のバランス" } ],
    answer: 3,
    exp: { vi:"Ưu tiên nên cân bằng giữa giá trị (tác động kinh doanh, rủi ro được giảm) và tính khả thi (nỗ lực, rủi ro, chi phí thấp). Chọn 'quick wins' tác động cao, khả thi cao tạo động lực và chứng minh giá trị sớm cho chương trình cải tiến.",
          en:"Prioritization should balance value (business impact, risk reduced) and feasibility (low effort, risk, cost). Choosing high-impact, high-feasibility 'quick wins' builds momentum and proves value early for the improvement program.",
          ja:"優先順位付けは価値（ビジネスインパクト、低減リスク）と実現性（低い工数・リスク・コスト）のバランスを取るべきです。高インパクトで実現性の高い「クイックウィン」を選ぶと勢いが生まれ、改善プログラムの価値を早期に証明できます。" } },

  { q: { vi:"Một tổ chức muốn dùng đo lường để chứng minh cải tiến quy trình có hiệu quả. Thiết kế đo lường nào cho phép so sánh trước/sau đáng tin cậy?",
        en:"An organization wants measurement to prove process improvement worked. Which measurement design allows a reliable before/after comparison?",
        ja:"組織は測定で改善の有効性を証明したい。信頼できる前後比較を可能にする測定設計はどれですか?" },
    options: [
      { vi:"Thiết lập đường cơ sở trước, đo cùng chỉ số nhất quán sau đó, và kiểm soát các biến gây nhiễu", en:"Establish a baseline first, measure the same metrics consistently afterward, and control confounding variables", ja:"先にベースラインを確立し、同じ指標を一貫して測定し、交絡変数を制御する" },
      { vi:"Chỉ đo sau khi cải tiến, không có đường cơ sở", en:"Measure only after improvement, with no baseline", ja:"改善後のみ測定し、ベースラインを持たない" },
      { vi:"Đổi định nghĩa chỉ số giữa hai lần đo", en:"Change the metric definition between the two measurements", ja:"2回の測定間で指標の定義を変える" },
      { vi:"Dùng cảm nhận chủ quan của quản lý", en:"Use the manager's subjective impression", ja:"マネージャーの主観的印象を使う" } ],
    answer: 0,
    exp: { vi:"Để so sánh trước/sau đáng tin cậy, cần đường cơ sở đo trước cải tiến, dùng cùng định nghĩa chỉ số nhất quán, và kiểm soát các yếu tố gây nhiễu (độ phức tạp dự án, quy mô nhóm). Đổi định nghĩa hay thiếu baseline khiến kết luận vô nghĩa.",
          en:"For a reliable before/after comparison, capture a baseline before improvement, use the same metric definitions consistently, and control confounders (project complexity, team size). Changing definitions or lacking a baseline makes conclusions meaningless.",
          ja:"信頼できる前後比較には、改善前のベースラインを取得し、同じ指標定義を一貫して使い、交絡要因（プロジェクト複雑度、チーム規模）を制御します。定義変更やベースライン欠如は結論を無意味にします。" } },

  { q: { vi:"Trong khung IDEAL, việc lập kế hoạch chi tiết cho các hành động cải tiến và phân bổ nguồn lực diễn ra ở giai đoạn nào?",
        en:"In IDEAL, detailed planning of improvement actions and resource allocation occurs in which phase?",
        ja:"IDEALで、改善アクションの詳細計画とリソース配分はどのフェーズで行われますか?" },
    options: [
      { vi:"Initiating", en:"Initiating", ja:"開始（Initiating）" },
      { vi:"Establishing", en:"Establishing", ja:"確立（Establishing）" },
      { vi:"Diagnosing", en:"Diagnosing", ja:"診断（Diagnosing）" },
      { vi:"Acting", en:"Acting", ja:"実行（Acting）" } ],
    answer: 1,
    exp: { vi:"Giai đoạn Establishing lập kế hoạch chi tiết: ưu tiên hóa, đặt mục tiêu đo được, phân bổ nguồn lực và lập kế hoạch hành động. Sau đó Acting mới thực thi các giải pháp, thí điểm và triển khai.",
          en:"The Establishing phase does detailed planning: prioritization, measurable goals, resource allocation and action planning. Acting then executes the solutions, pilots and rolls them out.",
          ja:"確立フェーズは詳細計画を行います。優先順位付け、測定可能な目標設定、リソース配分、アクション計画です。その後、実行が解決策を実施・試行・展開します。" } },

  { q: { vi:"Một quản lý phải trình bày rủi ro cho việc cắt giảm ngân sách kiểm thử 40%. Cách tiếp cận dựa trên rủi ro nào thuyết phục nhất?",
        en:"A manager must present the risk of cutting the test budget by 40%. Which risk-based approach is most convincing?",
        ja:"マネージャーはテスト予算40%削減のリスクを提示する。最も説得力のあるリスクベースのアプローチはどれですか?" },
    options: [
      { vi:"Nói rằng kiểm thử luôn quan trọng mà không dẫn chứng", en:"State that testing is always important without evidence", ja:"証拠なしにテストは常に重要だと述べる" },
      { vi:"Yêu cầu giữ nguyên ngân sách mà không giải thích", en:"Demand the budget stay unchanged without explanation", ja:"説明なしに予算維持を要求する" },
      { vi:"Định lượng các rủi ro sản phẩm sẽ không được xử lý, xác suất và tác động tiền/uy tín nếu chúng xảy ra", en:"Quantify which product risks would go uncovered, their probability and monetary/reputational impact if they occur", ja:"カバーされなくなる製品リスク、その発生確率と発生時の金銭的・評判的影響を定量化する" },
      { vi:"Đe dọa nghỉ việc", en:"Threaten to resign", ja:"辞職をちらつかせる" } ],
    answer: 2,
    exp: { vi:"Cách thuyết phục là gắn cắt giảm với rủi ro cụ thể: những vùng rủi ro sản phẩm nào sẽ không còn được kiểm thử, xác suất lỗi lọt ra sản xuất và tác động tiền/uy tín. Điều này cho lãnh đạo cơ sở để cân nhắc đánh đổi rủi ro-chi phí.",
          en:"The convincing approach ties the cut to concrete risk: which product risk areas lose coverage, the probability of escaped defects, and the monetary/reputational impact. This gives management a basis to weigh the risk-cost trade-off.",
          ja:"説得力のあるアプローチは、削減を具体的なリスクに結びつけます。どの製品リスク領域がカバーを失うか、欠陥流出の確率、金銭的・評判的影響です。これで経営層はリスクとコストのトレードオフを判断できます。" } },

  { q: { vi:"Sự khác biệt then chốt giữa 'test process improvement' và 'test process assessment' là gì?",
        en:"What is the key difference between 'test process improvement' and 'test process assessment'?",
        ja:"「テストプロセス改善」と「テストプロセスアセスメント」の主な違いは何ですか?" },
    options: [
      { vi:"Chúng hoàn toàn giống nhau", en:"They are entirely the same", ja:"完全に同じである" },
      { vi:"Improvement chỉ diễn ra một lần, assessment liên tục", en:"Improvement happens once, assessment is continuous", ja:"改善は一度きり、アセスメントは継続的である" },
      { vi:"Assessment chỉ dùng cho phần cứng", en:"Assessment is only for hardware", ja:"アセスメントはハードウェア専用である" },
      { vi:"Assessment đo lường và xác định hiện trạng/khoảng cách; improvement là hành động thay đổi để nâng cao dựa trên kết quả assessment", en:"Assessment measures and determines the current state/gaps; improvement is the action of changing to enhance, based on assessment results", ja:"アセスメントは現状・ギャップを測定・特定し、改善はその結果に基づき向上のために変更を実行する行為である" } ],
    answer: 3,
    exp: { vi:"Assessment xác định hiện trạng và khoảng cách so với mô hình/mục tiêu. Improvement là chuỗi hành động thực tế để thay đổi và nâng cao quy trình, thường dựa trên kết quả assessment. Assessment là đầu vào cho improvement.",
          en:"Assessment determines the current state and gaps against a model/goal. Improvement is the actual set of actions to change and enhance the process, typically driven by assessment results. Assessment feeds improvement.",
          ja:"アセスメントは、モデルや目標に対する現状とギャップを特定します。改善は、通常アセスメント結果に基づき、プロセスを変更・向上させる実際のアクション群です。アセスメントは改善の入力です。" } },

  { q: { vi:"Một nhóm phân tán gồm nhân sự nội bộ và nhà cung cấp thuê ngoài. Cấu trúc quản trị nào giảm rủi ro trách nhiệm không rõ ràng?",
        en:"A distributed team mixes internal staff and an outsourced vendor. Which governance structure reduces the risk of unclear accountability?",
        ja:"分散チームが社内スタッフと外部ベンダーを混在させる。責任の不明確さのリスクを減らすガバナンス構造はどれですか?" },
    options: [
      { vi:"RACI rõ ràng, điểm liên hệ duy nhất (SPOC), SLA và cơ chế báo cáo/leo thang thống nhất", en:"Clear RACI, a single point of contact (SPOC), SLAs and a unified reporting/escalation mechanism", ja:"明確なRACI、単一窓口（SPOC）、SLA、統一された報告・エスカレーション機構" },
      { vi:"Không phân định vai trò, để mọi người tự quyết", en:"No role definition, let everyone decide for themselves", ja:"役割を定めず、各自の判断に任せる" },
      { vi:"Chỉ liên lạc khi có sự cố nghiêm trọng", en:"Communicate only when a severe incident occurs", ja:"深刻なインシデント時のみ連絡する" },
      { vi:"Giao toàn bộ quyết định cho nhà cung cấp", en:"Delegate all decisions to the vendor", ja:"すべての決定をベンダーに委任する" } ],
    answer: 0,
    exp: { vi:"Trách nhiệm không rõ ràng là rủi ro lớn khi trộn nội bộ và thuê ngoài. Ma trận RACI, một điểm liên hệ duy nhất, SLA và cơ chế báo cáo/leo thang thống nhất làm rõ ai chịu trách nhiệm gì và đảm bảo phối hợp nhất quán.",
          en:"Unclear accountability is a major risk when mixing internal and outsourced staff. A RACI matrix, a single point of contact, SLAs and a unified reporting/escalation mechanism clarify who is responsible for what and ensure consistent coordination.",
          ja:"社内と外部委託を混在させる際、責任の不明確さは大きなリスクです。RACIマトリクス、単一窓口、SLA、統一された報告・エスカレーション機構が、誰が何に責任を持つかを明確にし、一貫した調整を保証します。" } },

  { q: { vi:"Khi lựa chọn chỉ số theo dõi tiến độ cải tiến quy trình dài hạn, đặc tính nào của chỉ số quan trọng nhất?",
        en:"When selecting metrics to track long-term process improvement progress, which metric property matters most?",
        ja:"長期的なプロセス改善の進捗を追跡する指標を選ぶ際、最も重要な特性は何ですか?" },
    options: [
      { vi:"Dễ thu thập nhưng không liên quan mục tiêu", en:"Easy to collect but unrelated to goals", ja:"収集は容易だが目標に無関係" },
      { vi:"Có thể so sánh nhất quán theo thời gian và phản ánh trực tiếp mục tiêu cải tiến (tính hợp lệ và ổn định)", en:"Consistently comparable over time and directly reflecting the improvement goal (validity and stability)", ja:"時間を通じて一貫して比較でき、改善目標を直接反映する（妥当性と安定性）" },
      { vi:"Thay đổi định nghĩa thường xuyên để linh hoạt", en:"Frequently redefined for flexibility", ja:"柔軟性のため頻繁に再定義される" },
      { vi:"Chỉ do một cá nhân hiểu được", en:"Understandable by only one individual", ja:"1人だけが理解できる" } ],
    answer: 1,
    exp: { vi:"Để theo dõi tiến bộ dài hạn, chỉ số phải hợp lệ (đo đúng thứ liên quan mục tiêu) và ổn định/nhất quán theo thời gian để so sánh xu hướng có ý nghĩa. Thay đổi định nghĩa liên tục phá vỡ khả năng so sánh.",
          en:"To track long-term progress, metrics must be valid (measure what relates to the goal) and stable/consistent over time so trends compare meaningfully. Constantly changing definitions destroys comparability.",
          ja:"長期的な進捗を追跡するには、指標が妥当（目標に関連するものを測定）で、時間を通じて安定・一貫している必要があり、傾向を有意に比較できます。定義を絶えず変えると比較可能性が失われます。" } },

  { q: { vi:"Một trưởng nhóm muốn tăng động lực cho nhóm kiểm thử. Theo các lý thuyết động lực, cách nào bền vững nhất?",
        en:"A lead wants to boost test team motivation. Per motivation theories, which approach is most sustainable?",
        ja:"リードはテストチームのモチベーションを高めたい。モチベーション理論によれば、最も持続的なアプローチはどれですか?" },
    options: [
      { vi:"Chỉ dựa vào thưởng tiền ngắn hạn", en:"Rely only on short-term monetary bonuses", ja:"短期的な金銭報酬のみに依存する" },
      { vi:"Tạo áp lực bằng đe dọa sa thải", en:"Apply pressure through threats of dismissal", ja:"解雇の脅しで圧力をかける" },
      { vi:"Kết hợp yếu tố tạo động lực nội tại: sự công nhận, trách nhiệm, cơ hội phát triển và ý nghĩa công việc", en:"Combine intrinsic motivators: recognition, responsibility, growth opportunities and meaningful work", ja:"内発的動機付け要因を組み合わせる：承認、責任、成長機会、仕事の意義" },
      { vi:"Giữ mọi người làm cùng một việc lặp lại mãi", en:"Keep everyone doing the same repetitive task forever", ja:"全員に同じ反復作業を永遠にさせる" } ],
    answer: 2,
    exp: { vi:"Các lý thuyết động lực (như Herzberg) chỉ ra rằng động lực bền vững đến từ yếu tố nội tại: công nhận, trách nhiệm, phát triển và ý nghĩa công việc. Thưởng tiền là yếu tố duy trì và đe dọa chỉ tạo động lực ngắn hạn, dễ phản tác dụng.",
          en:"Motivation theories (e.g. Herzberg) show sustainable motivation comes from intrinsic factors: recognition, responsibility, growth and meaningful work. Money is a hygiene factor and threats only motivate short-term and often backfire.",
          ja:"モチベーション理論（例：ハーズバーグ）は、持続的な動機付けが内発的要因（承認、責任、成長、仕事の意義）から生まれることを示します。金銭は衛生要因であり、脅しは短期的で逆効果になりがちです。" } },

  { q: { vi:"Tổ chức đang cân nhắc chọn TMMi hay TPI Next. Nếu ưu tiên là chứng nhận chính thức được công nhận rộng rãi bởi khách hàng và đấu thầu, lựa chọn nào phù hợp hơn?",
        en:"An organization is choosing between TMMi and TPI Next. If the priority is a widely recognized formal certification for customers and tenders, which fits better?",
        ja:"組織はTMMiとTPI Nextで迷う。顧客や入札で広く認められる正式な認証が優先なら、どちらが適していますか?" },
    options: [
      { vi:"TPI Next vì không có mức trưởng thành chính thức", en:"TPI Next because it has no formal maturity levels", ja:"正式な成熟度レベルがないTPI Next" },
      { vi:"Cả hai đều không hỗ trợ chứng nhận", en:"Neither supports certification", ja:"どちらも認証を支援しない" },
      { vi:"Chỉ CTP mới cấp chứng nhận", en:"Only CTP grants certification", ja:"CTPのみが認証を付与する" },
      { vi:"TMMi vì cung cấp chứng nhận mức trưởng thành chính thức thông qua đánh giá được công nhận", en:"TMMi because it provides formal maturity-level certification through recognized assessments", ja:"認定アセスメントを通じて正式な成熟度レベル認証を提供するTMMi" } ],
    answer: 3,
    exp: { vi:"TMMi có cơ chế đánh giá chính thức và cấp chứng nhận mức trưởng thành (1–5) được công nhận, hữu ích khi khách hàng/đấu thầu yêu cầu bằng chứng trưởng thành. TPI Next linh hoạt nhưng không cấp chứng nhận mức chính thức tương đương.",
          en:"TMMi has formal appraisals and grants recognized maturity-level certification (1-5), useful when customers/tenders require proof of maturity. TPI Next is flexible but does not grant an equivalent formal level certification.",
          ja:"TMMiは正式なアプレイザルを持ち、認められた成熟度レベル認証（1〜5）を付与し、顧客や入札が成熟度の証明を求める際に有用です。TPI Nextは柔軟ですが、同等の正式なレベル認証は付与しません。" } },

  { q: { vi:"Trong TMMi, mức 4 (Measured) bổ sung năng lực gì so với mức 3?",
        en:"In TMMi, what capability does Level 4 (Measured) add compared to Level 3?",
        ja:"TMMiで、レベル4（測定された）はレベル3と比べてどんな能力を追加しますか?" },
    options: [
      { vi:"Quản lý định lượng chất lượng và quy trình bằng đo lường thống kê, dự báo và đánh giá chất lượng sản phẩm", en:"Quantitative management of quality and process via statistical measurement, prediction and product quality evaluation", ja:"統計的測定、予測、製品品質評価による品質とプロセスの定量的管理" },
      { vi:"Chỉ đơn giản là viết thêm ca kiểm thử", en:"Simply writing more test cases", ja:"単に多くのテストケースを書くこと" },
      { vi:"Loại bỏ hoàn toàn việc lập kế hoạch", en:"Eliminating planning entirely", ja:"計画を完全に廃止すること" },
      { vi:"Chuyển toàn bộ sang thủ công", en:"Switching everything to manual", ja:"すべてを手動に切り替えること" } ],
    answer: 0,
    exp: { vi:"TMMi mức 4 (Measured) đưa vào quản lý định lượng: đo lường thống kê quy trình và sản phẩm, đánh giá chất lượng sản phẩm và dự báo dựa trên dữ liệu. Đây là bước tiến từ quy trình được định nghĩa (mức 3) sang quản lý bằng số liệu.",
          en:"TMMi Level 4 (Measured) introduces quantitative management: statistical measurement of process and product, product quality evaluation and data-based prediction. It advances from defined processes (Level 3) to numerically managed ones.",
          ja:"TMMiレベル4（測定された）は定量的管理を導入します。プロセスと製品の統計的測定、製品品質評価、データに基づく予測です。定義されたプロセス（レベル3）から数値管理へ前進します。" } },

  { q: { vi:"Một tổ chức phân phối kiểm thử giữa nhiều đối tác và thấy chất lượng biến động lớn giữa các đối tác. Biện pháp cải tiến quản trị nào phù hợp nhất?",
        en:"An organization spreads testing across several partners and sees large quality variation between them. Which governance improvement fits best?",
        ja:"組織はテストを複数のパートナーに分散させ、品質のばらつきが大きい。最も適したガバナンス改善はどれですか?" },
    options: [
      { vi:"Chấp nhận biến động vì không thể kiểm soát", en:"Accept the variation as uncontrollable", ja:"制御不能としてばらつきを受け入れる" },
      { vi:"Chuẩn hóa quy trình, tiêu chí chất lượng, mẫu tài liệu và đào tạo chung, kèm giám sát chỉ số thống nhất", en:"Standardize process, quality criteria, document templates and shared training, with unified metric monitoring", ja:"プロセス、品質基準、文書テンプレート、共通研修を標準化し、統一指標で監視する" },
      { vi:"Giao mỗi đối tác một tiêu chuẩn khác nhau", en:"Give each partner a different standard", ja:"各パートナーに異なる基準を与える" },
      { vi:"Chỉ chọn đối tác rẻ nhất", en:"Only select the cheapest partner", ja:"最も安いパートナーのみ選ぶ" } ],
    answer: 1,
    exp: { vi:"Biến động chất lượng giữa các đối tác thường do quy trình và tiêu chí không nhất quán. Chuẩn hóa quy trình, tiêu chí chất lượng, mẫu tài liệu, đào tạo chung và giám sát bằng bộ chỉ số thống nhất giúp đưa các đối tác về cùng chuẩn và kiểm soát chất lượng.",
          en:"Quality variation across partners usually stems from inconsistent processes and criteria. Standardizing process, quality criteria, templates and shared training, monitored by a unified metric set, brings partners to a common standard and controls quality.",
          ja:"パートナー間の品質のばらつきは通常、プロセスと基準の不一致に起因します。プロセス、品質基準、テンプレート、共通研修を標準化し、統一された指標セットで監視することで、パートナーを共通基準に揃え品質を制御できます。" } },

  { q: { vi:"Khi ước lượng lợi ích của cải tiến bằng phân tích giá trị hiện tại ròng (NPV), tại sao cần chiết khấu dòng tiền tương lai?",
        en:"When estimating improvement benefits with Net Present Value (NPV), why discount future cash flows?",
        ja:"正味現在価値（NPV）で改善の便益を見積もる際、なぜ将来のキャッシュフローを割り引くのですか?" },
    options: [
      { vi:"Vì tiền tương lai luôn nhiều hơn tiền hiện tại", en:"Because future money is always more than present money", ja:"将来のお金は常に現在より多いから" },
      { vi:"Để làm phép tính phức tạp hơn cho ấn tượng", en:"To make the calculation look more impressive", ja:"計算を複雑に見せて印象づけるため" },
      { vi:"Vì một đồng tiền trong tương lai có giá trị thấp hơn một đồng hiện tại do rủi ro và chi phí cơ hội theo thời gian", en:"Because a future unit of money is worth less than a present one due to risk and the time value of money", ja:"リスクと貨幣の時間価値により、将来の1単位は現在の1単位より価値が低いから" },
      { vi:"Vì kiểm thử không tạo ra tiền", en:"Because testing generates no money", ja:"テストはお金を生まないから" } ],
    answer: 2,
    exp: { vi:"NPV chiết khấu dòng tiền tương lai vì giá trị thời gian của tiền: một đồng nhận sau này đáng giá thấp hơn một đồng hôm nay do rủi ro và chi phí cơ hội. Điều này cho phép so sánh công bằng lợi ích trải dài nhiều năm của chương trình cải tiến.",
          en:"NPV discounts future cash flows because of the time value of money: a unit received later is worth less than one today due to risk and opportunity cost. This allows fair comparison of multi-year improvement benefits.",
          ja:"NPVは貨幣の時間価値のため将来のキャッシュフローを割り引きます。リスクと機会費用により、後で受け取る1単位は現在より価値が低いのです。これにより複数年にわたる改善便益を公平に比較できます。" } },

  { q: { vi:"Một chương trình cải tiến đã thí điểm một quy trình mới thành công ở một nhóm. Bước tiếp theo hợp lý trong giai đoạn Acting của IDEAL là gì?",
        en:"An improvement program has successfully piloted a new process in one team. What is the sensible next step in IDEAL's Acting phase?",
        ja:"改善プログラムが1つのチームで新プロセスの試行に成功した。IDEALの実行フェーズにおける次の合理的ステップは何ですか?" },
    options: [
      { vi:"Hủy bỏ quy trình mới vì đã thí điểm xong", en:"Cancel the new process because the pilot is done", ja:"試行が終わったので新プロセスを廃止する" },
      { vi:"Áp dụng ngay lập tức cho toàn tổ chức không điều chỉnh", en:"Apply it to the whole organization immediately with no adjustment", ja:"調整なしに即座に全組織へ適用する" },
      { vi:"Quên pilot và bắt đầu lại từ đầu", en:"Forget the pilot and start over", ja:"試行を忘れて最初からやり直す" },
      { vi:"Tinh chỉnh dựa trên bài học từ pilot rồi triển khai rộng một cách có kế hoạch", en:"Refine based on pilot lessons then roll out organization-wide in a planned manner", ja:"試行の教訓に基づき改良し、計画的に組織全体へ展開する" } ],
    answer: 3,
    exp: { vi:"Trong giai đoạn Acting, sau pilot thành công cần tinh chỉnh giải pháp dựa trên bài học rồi triển khai rộng theo kế hoạch, có hỗ trợ và giám sát. Triển khai ồ ạt không điều chỉnh dễ thất bại; hủy bỏ làm mất giá trị đã chứng minh.",
          en:"In Acting, after a successful pilot you refine the solution from lessons learned, then roll it out organization-wide in a planned, supported and monitored way. Mass rollout without adjustment risks failure; cancelling wastes proven value.",
          ja:"実行フェーズでは、試行成功後、得た教訓から解決策を改良し、計画的に支援・監視しながら組織全体へ展開します。調整なしの一斉展開は失敗リスクがあり、廃止は実証された価値を無駄にします。" } },

  { q: { vi:"Trong bối cảnh cải tiến, 'process champion' đóng vai trò gì?",
        en:"In an improvement context, what role does a 'process champion' play?",
        ja:"改善の文脈で「プロセスチャンピオン」はどんな役割を果たしますか?" },
    options: [
      { vi:"Người ủng hộ tích cực, thúc đẩy và duy trì động lực cho cải tiến, giúp vượt kháng cự và lan tỏa cam kết", en:"An active advocate who drives and sustains momentum, helps overcome resistance and spreads commitment", ja:"改善を積極的に支持・推進し勢いを維持し、抵抗の克服とコミットメントの浸透を助ける人" },
      { vi:"Người viết toàn bộ mã kiểm thử tự động", en:"The person who writes all the automation code", ja:"すべての自動化コードを書く人" },
      { vi:"Người duy nhất được phép chạy kiểm thử", en:"The only person allowed to run tests", ja:"テスト実行を許される唯一の人" },
      { vi:"Người phê duyệt ngân sách marketing", en:"The person approving the marketing budget", ja:"マーケティング予算を承認する人" } ],
    answer: 0,
    exp: { vi:"Process champion là người ủng hộ nhiệt thành cho chương trình cải tiến, thúc đẩy, duy trì động lực, giúp vượt qua kháng cự và truyền cảm hứng cam kết trong tổ chức. Vai trò này là yếu tố con người quan trọng cho thành công của cải tiến.",
          en:"A process champion is an enthusiastic advocate for the improvement program who drives it, sustains momentum, helps overcome resistance and inspires commitment across the organization. This human factor is key to improvement success.",
          ja:"プロセスチャンピオンは、改善プログラムを熱心に支持し、推進し、勢いを維持し、抵抗の克服を助け、組織全体にコミットメントを喚起する人です。この人的要因は改善成功の鍵です。" } },

  { q: { vi:"Một quản lý muốn đánh giá liệu chương trình cải tiến có đạt mục tiêu kinh doanh không, ngoài việc đạt mức trưởng thành. Thước đo nào phù hợp nhất?",
        en:"A manager wants to judge whether the improvement program met business goals, beyond reaching a maturity level. Which measure fits best?",
        ja:"マネージャーは、成熟度レベル到達を超えて改善プログラムがビジネス目標を達成したか判断したい。最も適した尺度はどれですか?" },
    options: [
      { vi:"Chỉ số nội bộ như số vùng quy trình đã đạt", en:"Internal metrics like number of process areas achieved", ja:"達成したプロセスエリア数などの内部指標" },
      { vi:"Kết quả kinh doanh: giảm chi phí lỗi sản xuất, rút ngắn time-to-market, tăng hài lòng khách hàng, ROI thực tế", en:"Business outcomes: reduced production defect cost, shorter time-to-market, higher customer satisfaction, actual ROI", ja:"ビジネス成果：本番欠陥コストの削減、市場投入時間の短縮、顧客満足の向上、実際のROI" },
      { vi:"Số cuộc họp cải tiến đã tổ chức", en:"Number of improvement meetings held", ja:"開催した改善会議の数" },
      { vi:"Số trang tài liệu quy trình mới", en:"Number of pages of new process docs", ja:"新プロセス文書のページ数" } ],
    answer: 1,
    exp: { vi:"Đạt mức trưởng thành là phương tiện, không phải mục đích cuối. Để chứng minh giá trị kinh doanh, cần đo kết quả thực: giảm chi phí lỗi, rút ngắn thời gian ra thị trường, tăng hài lòng khách hàng và ROI thực tế — gắn cải tiến với mục tiêu tổ chức.",
          en:"Reaching a maturity level is a means, not the end. To prove business value, measure real outcomes: reduced defect costs, shorter time-to-market, higher customer satisfaction and actual ROI - tying improvement to organizational goals.",
          ja:"成熟度レベル到達は目的ではなく手段です。ビジネス価値を証明するには、実際の成果を測定します。欠陥コスト削減、市場投入時間短縮、顧客満足向上、実際のROIで、改善を組織目標に結びつけます。" } }
];
