import { B } from "./content.mjs";

// CV tips category. Mix of builder-topics and explicit-page sample CVs.
const P = (heading, viBlocks, enBlocks) => ({ heading, blocks: { vi: viBlocks, en: enBlocks, ja: enBlocks } });

export const CV_CATEGORY = {
  slug: "cv-tips",
  title: B("Tip làm CV vượt ATS", "ATS-beating CV tips"),
  icon: "📄",
  topics: [
    // ---- Tip 1: structure ----
    {
      title: B("Cấu trúc CV Tester vượt bộ lọc ATS", "Tester CV structure that beats ATS"),
      summary: B("Bố cục 1 trang, đúng thứ tự, chuẩn máy đọc để lọt qua ATS và tới tay nhà tuyển dụng.",
        "One page, right order, machine-readable to pass ATS and reach a human recruiter."),
      objective: B("Hiểu ATS quét CV thế nào và trình bày để không bị loại oan trước khi người thật đọc.",
        "Understand how ATS scans CVs and format so you aren't rejected before a human reads it."),
      concept: B("ATS (Applicant Tracking System) là phần mềm quét CV, trích xuất thông tin theo từ khoá và loại CV không khớp hoặc khó đọc. CV thắng ATS phải dùng bố cục 1 cột đơn giản, tiêu đề mục chuẩn, không bảng/ảnh/cột phức tạp, và chứa đúng từ khoá trong JD.",
        "An ATS (Applicant Tracking System) parses CVs, extracts info by keywords and filters out non-matching or unreadable ones. An ATS-winning CV uses a simple single-column layout, standard section headers, no complex tables/images/columns, and mirrors the JD keywords."),
      steps: [
        B("Dùng bố cục 1 cột, font phổ biến (Arial/Calibri), .docx hoặc PDF text.", "Use single-column layout, common font (Arial/Calibri), .docx or text PDF."),
        B("Tiêu đề mục chuẩn: Summary, Skills, Experience, Projects, Education.", "Standard headers: Summary, Skills, Experience, Projects, Education."),
        B("Tránh bảng, text box, header/footer chứa thông tin quan trọng.", "Avoid tables, text boxes, headers/footers holding key info."),
        B("Rải từ khoá từ JD (Manual, Automation, Playwright, API, SQL...) tự nhiên.", "Weave JD keywords (Manual, Automation, Playwright, API, SQL...) naturally."),
        B("Đặt tên file: HoTen_Tester_CV.pdf.", "Name the file: FullName_Tester_CV.pdf."),
      ],
      example: {
        vi: "Thứ tự khối chuẩn cho Tester: 1) Thông tin liên hệ 2) Summary 3–4 dòng 3) Kỹ năng (chia nhóm) 4) Kinh nghiệm/Dự án (bullet có số liệu) 5) Học vấn & chứng chỉ (ISTQB nếu có).",
        en: "Standard block order for a Tester: 1) Contact 2) 3–4 line summary 3) Skills (grouped) 4) Experience/Projects (metric bullets) 5) Education & certs (ISTQB if any).",
      },
      pitfalls: [
        B("CV 2 cột đẹp mắt nhưng ATS đọc lộn xộn.", "Pretty 2-column CVs that ATS parses as garbled."),
        B("Nhét thông tin vào ảnh — ATS không đọc được.", "Putting info in images — ATS can't read them."),
        B("Dùng tiêu đề sáng tạo lạ khiến ATS không nhận diện mục.", "Creative section titles ATS can't recognize."),
      ],
      onJob: B("Nhiều công ty (đặc biệt tập đoàn, outsourcing lớn) lọc CV tự động trước. CV rớt ở bước này thì nhà tuyển dụng không bao giờ thấy bạn giỏi.",
        "Many companies (especially large corps and big outsourcing firms) auto-filter first. If your CV fails here, no recruiter ever sees how good you are."),
      aiTip: B("Dán JD + CV vào AI, hỏi 'CV của tôi thiếu từ khoá quan trọng nào so với JD này?' để tối ưu khớp.",
        "Paste the JD + your CV into AI and ask 'which important keywords does my CV miss vs this JD?' to optimize the match."),
      checklist: [
        B("Bố cục 1 cột, không bảng/ảnh chứa chữ quan trọng.", "Single column, no tables/images holding key text."),
        B("Chứa từ khoá khớp JD.", "Contains JD-matching keywords."),
        B("Xuất PDF dạng text (chọn/copy được).", "Export as text PDF (selectable/copyable)."),
      ],
    },
    // ---- Tip 2: summary + achievements ----
    {
      title: B("Viết Summary & mô tả kinh nghiệm gây ấn tượng", "Write an impressive summary & experience"),
      summary: B("Dùng công thức STAR + số liệu để mỗi dòng chứng minh giá trị, không liệt kê nhiệm vụ.",
        "Use STAR + metrics so every line proves value instead of listing duties."),
      objective: B("Biến CV 'liệt kê việc' thành CV 'chứng minh kết quả' khiến nhà tuyển dụng muốn gọi phỏng vấn.",
        "Turn a 'duties list' CV into a 'proven results' CV recruiters want to call."),
      concept: B("Nhà tuyển dụng đọc CV trong ~7 giây. Summary 3–4 dòng phải nêu: bạn là ai, thế mạnh, và giá trị mang lại. Mỗi bullet kinh nghiệm nên theo STAR (Tình huống–Nhiệm vụ–Hành động–Kết quả) và kèm SỐ LIỆU để đo lường tác động.",
        "Recruiters skim in ~7 seconds. A 3–4 line summary must state who you are, your strengths and the value you bring. Each experience bullet should follow STAR (Situation–Task–Action–Result) with METRICS to quantify impact."),
      steps: [
        B("Viết summary: vai trò + số năm + thế mạnh + công nghệ chính.", "Summary: role + years + strengths + core tech."),
        B("Mỗi bullet bắt đầu bằng động từ mạnh (Designed, Automated, Reduced).", "Start each bullet with a strong verb (Designed, Automated, Reduced)."),
        B("Thêm số liệu: giảm bao nhiêu %, tiết kiệm bao nhiêu giờ, bắt bao nhiêu bug.", "Add metrics: % reduced, hours saved, bugs caught."),
        B("Gắn với công nghệ & phạm vi thực tế.", "Tie to real tech & scope."),
      ],
      example: {
        vi: "Yếu: 'Viết test case và test chức năng.' → Mạnh: 'Thiết kế 300+ test case và tự động hoá bộ regression bằng Playwright, giảm 60% thời gian kiểm thử mỗi release và phát hiện 40+ lỗi trước production.'",
        en: "Weak: 'Wrote test cases and tested features.' → Strong: 'Designed 300+ test cases and automated the regression suite with Playwright, cutting per-release test time by 60% and catching 40+ pre-production bugs.'",
      },
      pitfalls: [
        B("Liệt kê nhiệm vụ chung chung, không có kết quả.", "Listing generic duties with no results."),
        B("Không có số liệu nào.", "Zero metrics."),
        B("Summary sáo rỗng kiểu 'chăm chỉ, ham học hỏi'.", "Cliché summary like 'hardworking, eager to learn'."),
      ],
      onJob: B("CV có số liệu tạo ấn tượng 'ứng viên tạo ra tác động'. Đây là điểm khác biệt lớn nhất giữa CV được gọi và bị bỏ qua.",
        "Metric-driven CVs signal an 'impact-maker'. It's the biggest differentiator between a called-back CV and an ignored one."),
      aiTip: B("Nhờ AI viết lại bullet của bạn theo STAR và gợi ý số liệu cần bổ sung (bạn điền số thật).",
        "Ask AI to rewrite your bullets in STAR form and suggest which metrics to add (you fill real numbers)."),
      checklist: [
        B("Summary nêu rõ giá trị trong 3–4 dòng.", "Summary states value in 3–4 lines."),
        B("Mỗi bullet có động từ mạnh + số liệu.", "Each bullet has a strong verb + metric."),
      ],
    },
  ],
  // ---- Explicit sample CVs (rendered as-is) ----
  samples: [
    {
      title: B("CV mẫu — Fresher Manual Tester", "Sample CV — Fresher Manual Tester"),
      summary: B("Mẫu CV cho người mới, chưa kinh nghiệm nhưng vẫn ấn tượng nhờ dự án thực hành.",
        "A fresher CV template — no job experience yet, still impressive via practice projects."),
      pages: [
        P(B("Thông tin & Summary", "Header & Summary"),
          [{ t: "h", text: "NGUYỄN VĂN A — Manual Tester (Fresher)" },
           { t: "p", text: "📧 vana@email.com · 📱 0900 000 000 · 📍 TP.HCM · github.com/vana" },
           { t: "h", text: "SUMMARY" },
           { t: "p", text: "Fresher QA/Tester được đào tạo bài bản về manual testing, thiết kế test case và kiểm thử API. Đã hoàn thành 3 dự án thực hành end-to-end, thành thạo Postman, SQL cơ bản và quy trình bug tracking trên Jira. Ham học automation, mục tiêu trở thành Automation QA trong 12 tháng." }],
          [{ t: "h", text: "NGUYEN VAN A — Manual Tester (Fresher)" },
           { t: "p", text: "📧 vana@email.com · 📱 0900 000 000 · 📍 HCMC · github.com/vana" },
           { t: "h", text: "SUMMARY" },
           { t: "p", text: "Trained fresher QA/Tester skilled in manual testing, test-case design and API testing. Completed 3 hands-on end-to-end projects; proficient with Postman, basic SQL and Jira bug tracking. Eager to grow into an Automation QA within 12 months." }]),
        P(B("Kỹ năng & Chứng chỉ", "Skills & Certs"),
          [{ t: "h", text: "SKILLS" },
           { t: "ul", items: ["Manual testing: test case design, exploratory, regression, smoke", "Techniques: Equivalence Partitioning, Boundary Value, Decision Table", "API testing: Postman, REST, JSON, status/schema assertions", "Database: SQL SELECT/JOIN cơ bản để kiểm dữ liệu", "Tools: Jira, TestRail, Git cơ bản"] },
           { t: "h", text: "CERTIFICATE" },
           { t: "ul", items: ["ISTQB Foundation Level (dự kiến/đã có)", "CyberSoft Tester Bootcamp"] }],
          [{ t: "h", text: "SKILLS" },
           { t: "ul", items: ["Manual testing: test case design, exploratory, regression, smoke", "Techniques: Equivalence Partitioning, Boundary Value, Decision Table", "API testing: Postman, REST, JSON, status/schema assertions", "Database: basic SQL SELECT/JOIN for data checks", "Tools: Jira, TestRail, basic Git"] },
           { t: "h", text: "CERTIFICATE" },
           { t: "ul", items: ["ISTQB Foundation Level (planned/obtained)", "CyberSoft Tester Bootcamp"] }]),
        P(B("Dự án thực hành", "Practice Projects"),
          [{ t: "h", text: "PROJECTS" },
           { t: "p", text: "E-commerce Web — Kiểm thử chức năng (2024)" },
           { t: "ul", items: ["Thiết kế 120+ test case cho luồng đăng ký, giỏ hàng, thanh toán.", "Phát hiện & báo cáo 25 lỗi trên Jira với bằng chứng đầy đủ.", "Kiểm thử API giỏ hàng bằng Postman, viết assertion status + schema."] },
           { t: "p", text: "Banking App — Kiểm thử API (2024)" },
           { t: "ul", items: ["Viết 40 ca test API chuyển khoản gồm ca lỗi & phân quyền.", "Dùng SQL đối chiếu dữ liệu giao dịch sau mỗi request."] }],
          [{ t: "h", text: "PROJECTS" },
           { t: "p", text: "E-commerce Web — Functional testing (2024)" },
           { t: "ul", items: ["Designed 120+ test cases for register, cart, checkout flows.", "Found & reported 25 bugs in Jira with full evidence.", "API-tested the cart with Postman, wrote status + schema assertions."] },
           { t: "p", text: "Banking App — API testing (2024)" },
           { t: "ul", items: ["Wrote 40 transfer API cases incl. error & authorization cases.", "Used SQL to reconcile transaction data after each request."] }]),
      ],
    },
    {
      title: B("CV mẫu — Automation QA (2+ năm)", "Sample CV — Automation QA (2+ yrs)"),
      summary: B("Mẫu CV automation nhấn số liệu, Playwright/CI và tác động kinh doanh.",
        "An automation CV emphasizing metrics, Playwright/CI and business impact."),
      pages: [
        P(B("Thông tin & Summary", "Header & Summary"),
          [{ t: "h", text: "TRẦN THỊ B — Automation QA Engineer" },
           { t: "p", text: "📧 thib@email.com · 📱 0911 111 111 · 📍 Hà Nội · linkedin.com/in/thib" },
           { t: "h", text: "SUMMARY" },
           { t: "p", text: "Automation QA 2+ năm, chuyên E2E với Playwright & API automation. Xây dựng framework POM chạy trong CI (GitHub Actions), giảm 65% thời gian regression và nâng độ ổn định test lên 98%. Tư duy AI-native: dùng LLM tăng tốc thiết kế test và điều tra log." }],
          [{ t: "h", text: "TRAN THI B — Automation QA Engineer" },
           { t: "p", text: "📧 thib@email.com · 📱 0911 111 111 · 📍 Hanoi · linkedin.com/in/thib" },
           { t: "h", text: "SUMMARY" },
           { t: "p", text: "Automation QA with 2+ years, specialized in E2E with Playwright & API automation. Built a POM framework running in CI (GitHub Actions), cutting regression time 65% and raising test stability to 98%. AI-native: uses LLMs to speed up test design and log triage." }]),
        P(B("Kỹ năng", "Skills"),
          [{ t: "h", text: "SKILLS" },
           { t: "ul", items: ["Automation: Playwright, Selenium, Page Object Model, fixtures", "API: REST assured/Postman/Newman, schema & contract testing", "CI/CD: GitHub Actions, sharding, HTML report + trace", "Performance: k6 cơ bản (load, p95/p99)", "Ngôn ngữ: JavaScript/TypeScript, SQL", "AI: prompt cho sinh test, self-healing, visual testing (Percy)"] }],
          [{ t: "h", text: "SKILLS" },
           { t: "ul", items: ["Automation: Playwright, Selenium, Page Object Model, fixtures", "API: REST assured/Postman/Newman, schema & contract testing", "CI/CD: GitHub Actions, sharding, HTML report + trace", "Performance: basic k6 (load, p95/p99)", "Languages: JavaScript/TypeScript, SQL", "AI: prompts for test gen, self-healing, visual testing (Percy)"] }]),
        P(B("Kinh nghiệm", "Experience"),
          [{ t: "h", text: "EXPERIENCE" },
           { t: "p", text: "QA Automation Engineer — Công ty X (2023–nay)" },
           { t: "ul", items: ["Xây framework Playwright + POM cho 200+ ca E2E, chạy song song 4 shard trong CI.", "Giảm thời gian regression từ 90→30 phút (−65%), tăng tần suất release.", "Đưa API automation vào pipeline, chặn 30+ lỗi trước khi lên production/quý.", "Giảm tỉ lệ flaky từ 12%→2% bằng chờ điều kiện & cô lập dữ liệu."] },
           { t: "p", text: "Manual QA — Công ty Y (2022–2023)" },
           { t: "ul", items: ["Thiết kế test case & kiểm thử 3 sản phẩm web/mobile.", "Chủ động chuyển sang automation, tự học Playwright."] }],
          [{ t: "h", text: "EXPERIENCE" },
           { t: "p", text: "QA Automation Engineer — Company X (2023–present)" },
           { t: "ul", items: ["Built a Playwright + POM framework for 200+ E2E cases, 4-shard parallel CI.", "Cut regression time 90→30 min (−65%), enabling more frequent releases.", "Added API automation to the pipeline, blocking 30+ bugs/quarter pre-production.", "Reduced flaky rate 12%→2% via condition waits & data isolation."] },
           { t: "p", text: "Manual QA — Company Y (2022–2023)" },
           { t: "ul", items: ["Designed test cases & tested 3 web/mobile products.", "Proactively moved into automation, self-taught Playwright."] }]),
      ],
    },
  ],
};
