import { B } from "./content.mjs";

// Real Tester interview bank. cat = interview category slug.
// MCQ: answer is the 0-based index of the correct option.

export const IV_CATEGORIES = [
  { slug: "iv-manual", title: B("Phỏng vấn Manual Testing", "Manual Testing Interview", "手動テストの面接") },
  { slug: "iv-automation", title: B("Phỏng vấn Automation", "Automation Interview", "自動化テストの面接") },
  { slug: "iv-playwright", title: B("Phỏng vấn Playwright & CI", "Playwright & CI Interview", "PlaywrightとCIの面接") },
  { slug: "iv-ai", title: B("Phỏng vấn AI in Testing", "AI in Testing Interview", "テストにおけるAIの面接") },
];

const O = (vi, en, ja) => ({ vi, en, ja: ja ?? en });

export const MCQ = [
  { cat: "iv-manual", q: B("Mục tiêu chính của kiểm thử phần mềm là gì?", "What is the main goal of software testing?", "ソフトウェアテストの主な目的は何ですか？"),
    options: [O("Chứng minh không còn lỗi", "Prove there are no bugs", "バグが存在しないことを証明する"), O("Tìm lỗi và giảm rủi ro", "Find defects and reduce risk", "欠陥を見つけてリスクを減らす"),
      O("Làm chậm quá trình phát hành", "Slow down releases", "リリースを遅らせる"), O("Thay thế lập trình viên", "Replace developers", "開発者を置き換える")],
    answer: 1, exp: B("Kiểm thử nhằm phát hiện lỗi và giảm rủi ro; không thể chứng minh 'hoàn toàn không có lỗi'.", "Testing finds defects and reduces risk; it can't prove the total absence of bugs.", "テストは欠陥を発見しリスクを減らすためのものであり、「バグが完全に存在しないこと」は証明できません。") },
  { cat: "iv-manual", q: B("Severity và Priority khác nhau thế nào?", "How do Severity and Priority differ?", "重要度（Severity）と優先度（Priority）はどう違いますか？"),
    options: [O("Chúng giống hệt nhau", "They are identical", "両者は同一である"), O("Severity = mức nghiêm trọng kỹ thuật, Priority = mức cần fix trước", "Severity = technical impact, Priority = how soon to fix", "重要度＝技術的な影響度、優先度＝どれだけ早く修正すべきか"),
      O("Priority do dev quyết, Severity do khách quyết", "Priority set by dev, Severity by customer", "優先度は開発者が、重要度は顧客が決める"), O("Chỉ dùng trong automation", "Only used in automation", "自動化でのみ使われる")],
    answer: 1, exp: B("Severity là mức ảnh hưởng kỹ thuật; Priority là thứ tự cần xử lý theo nghiệp vụ.", "Severity is technical impact; Priority is the business order of fixing.", "重要度は技術的な影響度であり、優先度は業務上の対応順序です。") },
  { cat: "iv-manual", q: B("Kỹ thuật Boundary Value Analysis tập trung vào đâu?", "Boundary Value Analysis focuses on what?", "境界値分析（Boundary Value Analysis）は何に注目しますか？"),
    options: [O("Giá trị giữa vùng", "Mid-range values", "範囲の中間の値"), O("Giá trị tại ranh giới các phân vùng", "Values at partition boundaries", "分割の境界にある値"),
      O("Giá trị ngẫu nhiên", "Random values", "ランダムな値"), O("Chỉ giá trị hợp lệ", "Only valid values", "有効な値のみ")],
    answer: 1, exp: B("Lỗi thường xảy ra ở biên nên BVA test min/max và lân cận.", "Bugs cluster at edges, so BVA tests min/max and neighbors.", "バグは境界に集中しやすいため、境界値分析では最小値・最大値とその近傍をテストします。") },
  { cat: "iv-manual", q: B("Smoke test dùng để làm gì?", "What is a smoke test for?", "スモークテストは何のために行いますか？"),
    options: [O("Kiểm thử toàn bộ chi tiết", "Exhaustive detailed testing", "網羅的で詳細なテスト"), O("Kiểm nhanh các chức năng chính còn chạy sau build", "Quickly verify core features still work after a build", "ビルド後に主要機能が動作するかを素早く確認する"),
      O("Test hiệu năng dưới tải", "Load performance testing", "負荷時の性能テスト"), O("Test bảo mật", "Security testing", "セキュリティテスト")],
    answer: 1, exp: B("Smoke test xác nhận build đủ ổn định để test sâu hơn.", "Smoke tests confirm the build is stable enough for deeper testing.", "スモークテストは、ビルドがより深いテストに耐えるほど安定しているかを確認します。") },
  { cat: "iv-manual", q: B("Regression testing nghĩa là gì?", "What is regression testing?", "リグレッションテストとは何ですか？"),
    options: [O("Test tính năng mới lần đầu", "Testing a new feature for the first time", "新機能を初めてテストすること"), O("Test lại để đảm bảo thay đổi không phá vỡ chức năng cũ", "Re-testing to ensure changes didn't break existing features", "変更が既存機能を壊していないか再確認すること"),
      O("Chỉ test giao diện", "UI-only testing", "UIのみのテスト"), O("Test khi hệ thống sập", "Testing after a crash", "システムクラッシュ後のテスト")],
    answer: 1, exp: B("Regression đảm bảo code mới không làm hỏng chức năng đang chạy.", "Regression ensures new code didn't break working functionality.", "リグレッションテストは、新しいコードが既存の動作を壊していないことを保証します。") },
  { cat: "iv-manual", q: B("Điều gì làm một test case tốt?", "What makes a good test case?", "良いテストケースの条件は何ですか？"),
    options: [O("Càng dài càng tốt", "The longer the better", "長ければ長いほど良い"), O("Rõ ràng, độc lập, có kết quả mong đợi cụ thể", "Clear, independent, with a concrete expected result", "明確で独立しており、具体的な期待結果がある"),
      O("Không cần kết quả mong đợi", "No expected result needed", "期待結果は不要"), O("Chỉ cần tiêu đề", "Just a title", "タイトルだけあればよい")],
    answer: 1, exp: B("Test case tốt phải tái lập được và có kết quả mong đợi rõ ràng.", "A good test case is reproducible with a clear expected result.", "良いテストケースは再現可能で、明確な期待結果を持ちます。") },
  { cat: "iv-automation", q: B("Test pyramid khuyến nghị điều gì?", "What does the test pyramid recommend?", "テストピラミッドは何を推奨しますか？"),
    options: [O("Nhiều UI test, ít unit test", "Many UI tests, few unit tests", "UIテストを多く、ユニットテストを少なく"), O("Nhiều unit/API test, ít UI test", "Many unit/API tests, few UI tests", "ユニット／APIテストを多く、UIテストを少なく"),
      O("Chỉ test thủ công", "Only manual testing", "手動テストのみ"), O("Bỏ qua unit test", "Skip unit tests", "ユニットテストを省く")],
    answer: 1, exp: B("Kim tự tháp: nhiều test rẻ & nhanh (unit/API) ở đáy, ít E2E ở đỉnh.", "Pyramid: many cheap/fast tests (unit/API) at the base, few E2E at the top.", "ピラミッドでは、安価で高速なテスト（ユニット／API）を土台に多く、E2Eを頂点に少なく配置します。") },
  { cat: "iv-automation", q: B("Page Object Model giúp giải quyết vấn đề gì?", "What problem does the Page Object Model solve?", "ページオブジェクトモデル（POM）はどんな問題を解決しますか？"),
    options: [O("Tăng tốc mạng", "Faster network", "ネットワークを高速化する"), O("Tập trung locator để dễ bảo trì khi UI đổi", "Centralizes locators for easy maintenance when UI changes", "ロケーターを一元管理し、UI変更時の保守を容易にする"),
      O("Loại bỏ nhu cầu assertion", "Removes the need for assertions", "アサーションを不要にする"), O("Chạy test không cần trình duyệt", "Runs tests without a browser", "ブラウザなしでテストを実行する")],
    answer: 1, exp: B("POM tách locator/hành động khỏi test, sửa 1 nơi khi UI thay đổi.", "POM separates locators/actions from tests; fix one place on UI change.", "POMはロケーターや操作をテストから分離するため、UI変更時は一箇所を直すだけで済みます。") },
  { cat: "iv-automation", q: B("Flaky test là gì?", "What is a flaky test?", "フレーキーテストとは何ですか？"),
    options: [O("Test luôn fail", "A test that always fails", "常に失敗するテスト"), O("Test lúc pass lúc fail dù code không đổi", "A test that passes/fails without code changes", "コードが変わらないのに成功したり失敗したりするテスト"),
      O("Test chạy quá nhanh", "A test that runs too fast", "実行が速すぎるテスト"), O("Test không có assertion", "A test without assertions", "アサーションのないテスト")],
    answer: 1, exp: B("Flaky thường do timing, dữ liệu chia sẻ hoặc phụ thuộc thứ tự.", "Flakiness usually stems from timing, shared data or order dependency.", "フレーキーさは通常、タイミング、共有データ、または実行順序への依存に起因します。") },
  { cat: "iv-automation", q: B("Cách tốt nhất để chờ một phần tử trong test hiện đại?", "Best way to wait for an element in modern tests?", "現代的なテストで要素を待つ最善の方法は？"),
    options: [O("sleep(5000) cố định", "A fixed sleep(5000)", "固定の sleep(5000)"), O("Chờ theo điều kiện (element visible / network idle)", "Condition-based wait (element visible / network idle)", "条件ベースの待機（要素の表示／ネットワークのアイドル）"),
      O("Vòng lặp while vô hạn", "An infinite while loop", "無限のwhileループ"), O("Không cần chờ", "No waiting needed", "待機は不要")],
    answer: 1, exp: B("Chờ theo điều kiện ổn định và nhanh hơn sleep cứng.", "Condition waits are more stable and faster than hard sleeps.", "条件ベースの待機は、固定スリープより安定していて高速です。") },
  { cat: "iv-automation", q: B("Selector nào ổn định nhất cho automation?", "Which selector is most stable for automation?", "自動化に最も安定したセレクターはどれですか？"),
    options: [O("Class CSS sinh tự động", "Auto-generated CSS classes", "自動生成されたCSSクラス"), O("data-testid hoặc role", "data-testid or role", "data-testid またはロール（role）"),
      O("XPath tuyệt đối dài", "A long absolute XPath", "長い絶対XPath"), O("Thứ tự index của thẻ", "Element index order", "要素のインデックス順")],
    answer: 1, exp: B("data-testid/role ít thay đổi theo style, giúp test bền.", "data-testid/role rarely change with styling, keeping tests robust.", "data-testidやロールはスタイル変更の影響を受けにくく、テストを堅牢に保ちます。") },
  { cat: "iv-playwright", q: B("Đặc điểm nổi bật của Playwright so với Selenium?", "A standout Playwright feature vs Selenium?", "Seleniumに比べたPlaywrightの際立った特徴は？"),
    options: [O("Không hỗ trợ nhiều trình duyệt", "No multi-browser support", "マルチブラウザ非対応"), O("Auto-wait tích hợp và trace viewer", "Built-in auto-wait and trace viewer", "組み込みの自動待機とトレースビューア"),
      O("Chỉ chạy trên Windows", "Windows-only", "Windows専用"), O("Không chạy được trong CI", "Can't run in CI", "CIで実行できない")],
    answer: 1, exp: B("Playwright auto-wait và có trace viewer để debug từng bước.", "Playwright auto-waits and offers a trace viewer to debug each step.", "Playwrightは自動待機を行い、各ステップをデバッグできるトレースビューアを備えています。") },
  { cat: "iv-playwright", q: B("Sharding trong Playwright CI để làm gì?", "What is sharding in Playwright CI for?", "PlaywrightのCIにおけるシャーディングは何のためですか？"),
    options: [O("Mã hoá dữ liệu", "Encrypting data", "データを暗号化する"), O("Chia test cho nhiều máy chạy song song", "Splitting tests across machines to run in parallel", "テストを複数マシンに分割して並列実行する"),
      O("Gộp báo cáo", "Merging reports", "レポートを統合する"), O("Tự sửa locator", "Auto-fixing locators", "ロケーターを自動修正する")],
    answer: 1, exp: B("Sharding chia bộ test để chạy song song, rút ngắn thời gian CI.", "Sharding splits the suite to run in parallel, cutting CI time.", "シャーディングはテストスイートを分割して並列実行し、CI時間を短縮します。") },
  { cat: "iv-playwright", q: B("Web-first assertion trong Playwright có ưu điểm gì?", "Advantage of web-first assertions in Playwright?", "Playwrightのweb-firstアサーションの利点は？"),
    options: [O("Không bao giờ fail", "They never fail", "決して失敗しない"), O("Tự retry đến khi điều kiện đúng hoặc hết timeout", "Auto-retry until the condition holds or timeout", "条件が満たされるかタイムアウトするまで自動リトライする"),
      O("Chạy nhanh hơn nhờ bỏ kiểm tra", "Faster by skipping checks", "チェックを省いて速くする"), O("Chỉ dùng cho API", "API only", "API専用")],
    answer: 1, exp: B("expect(locator) tự chờ & retry, giảm flaky.", "expect(locator) auto-waits & retries, reducing flakiness.", "expect(locator)は自動で待機・リトライを行い、フレーキーさを減らします。") },
  { cat: "iv-ai", q: B("Rủi ro lớn khi dùng LLM để sinh test case?", "A key risk of using LLMs to generate test cases?", "LLMでテストケースを生成する際の大きなリスクは？"),
    options: [O("Chạy quá nhanh", "Too fast", "速すぎる"), O("Có thể 'ảo giác' nội dung sai, cần kiểm chứng", "It can hallucinate wrong content; must be validated", "誤った内容をハルシネーションする可能性があり、検証が必要"),
      O("Luôn thiếu ca negative", "Always lacks negative cases", "常にネガティブケースが不足する"), O("Không viết được tiếng Việt", "Can't write Vietnamese", "ベトナム語が書けない")],
    answer: 1, exp: B("LLM có thể tạo nội dung sai; luôn đối chiếu requirement thật.", "LLMs can produce wrong content; always cross-check the real requirement.", "LLMは誤った内容を生成することがあるため、必ず実際の要件と照合してください。") },
  { cat: "iv-ai", q: B("Điều KHÔNG nên làm khi dùng AI trong testing?", "What should you NOT do when using AI in testing?", "テストでAIを使う際にしてはいけないことは？"),
    options: [O("Kiểm chứng output", "Validate the output", "出力を検証する"), O("Dán dữ liệu nhạy cảm/PII thật vào prompt", "Paste real sensitive/PII data into prompts", "実際の機密・個人情報（PII）をプロンプトに貼り付ける"),
      O("Dùng AI liệt kê ca biên", "Use AI to list edge cases", "AIで境界ケースを列挙する"), O("Lưu prompt tái sử dụng", "Save reusable prompts", "再利用可能なプロンプトを保存する")],
    answer: 1, exp: B("Không đưa dữ liệu nhạy cảm thật vào prompt vì rủi ro rò rỉ.", "Never paste real sensitive data into prompts due to leakage risk.", "漏洩リスクがあるため、実際の機密データをプロンプトに入力してはいけません。") },
  { cat: "iv-ai", q: B("Visual testing bằng AI giúp bắt loại lỗi nào?", "AI visual testing catches which defects?", "AIによるビジュアルテストはどんな欠陥を検出しますか？"),
    options: [O("Lỗi logic backend", "Backend logic bugs", "バックエンドのロジックバグ"), O("Lệch layout, màu, chữ mà assertion chức năng bỏ sót", "Layout/color/text shifts functional assertions miss", "機能アサーションが見逃すレイアウト・色・文字のずれ"),
      O("Lỗi cơ sở dữ liệu", "Database errors", "データベースのエラー"), O("Lỗi bảo mật", "Security flaws", "セキュリティの欠陥")],
    answer: 1, exp: B("Visual diff phát hiện thay đổi giao diện ngoài phạm vi test chức năng.", "Visual diffs catch UI changes outside functional test scope.", "ビジュアル差分は、機能テストの範囲外にあるUIの変化を検出します。") },
];

export const ESSAY = [
  { cat: "iv-manual", q: B("Trình bày quy trình bạn xử lý một bug production nghiêm trọng.", "Describe how you handle a critical production bug.", "本番環境の重大なバグをどう対処するか、その手順を説明してください。"),
    keywords: ["reproduce", "log", "severity", "priority", "root cause", "regression", "communicate"],
    exp: B("Tái hiện, thu thập log, đánh giá severity/priority, tìm nguyên nhân gốc, verify & regression, truyền thông stakeholder.", "Reproduce, gather logs, assess severity/priority, find root cause, verify & regression, communicate to stakeholders.", "再現し、ログを収集し、重要度・優先度を評価し、根本原因を特定し、検証とリグレッションを行い、ステークホルダーに連携します。") },
  { cat: "iv-manual", q: B("Bạn thiết kế test cho một form đăng ký như thế nào?", "How do you design tests for a registration form?", "登録フォームのテストをどのように設計しますか？"),
    keywords: ["positive", "negative", "boundary", "validation", "required", "duplicate", "security"],
    exp: B("Ca positive/negative/boundary, validation từng field, required, trùng email, và khía cạnh bảo mật.", "Positive/negative/boundary cases, per-field validation, required, duplicate email, and security aspects.", "ポジティブ・ネガティブ・境界値のケース、各項目のバリデーション、必須入力、メール重複、そしてセキュリティの観点を確認します。") },
  { cat: "iv-automation", q: B("Chiến lược của bạn để giảm flaky test trong CI là gì?", "What is your strategy to reduce flaky tests in CI?", "CIでフレーキーテストを減らすためのあなたの戦略は何ですか？"),
    keywords: ["wait", "isolate", "data", "independent", "retry", "network", "stable selector"],
    exp: B("Chờ theo điều kiện, cô lập dữ liệu, test độc lập, retry có kiểm soát, selector ổn định.", "Condition waits, data isolation, independent tests, controlled retry, stable selectors.", "条件ベースの待機、データの隔離、独立したテスト、制御されたリトライ、安定したセレクターを用います。") },
  { cat: "iv-automation", q: B("Làm sao quyết định test nào nên tự động hoá?", "How do you decide what to automate?", "どのテストを自動化すべきかをどう判断しますか？"),
    keywords: ["roi", "frequency", "stable", "regression", "maintenance", "risk"],
    exp: B("Dựa trên ROI, tần suất chạy, độ ổn định, rủi ro và chi phí bảo trì.", "Based on ROI, run frequency, stability, risk and maintenance cost.", "ROI、実行頻度、安定性、リスク、保守コストに基づいて判断します。") },
  { cat: "iv-playwright", q: B("Giải thích cách bạn tổ chức một dự án Playwright thực chiến.", "Explain how you structure a real Playwright project.", "実践的なPlaywrightプロジェクトをどう構成するか説明してください。"),
    keywords: ["page object", "fixture", "config", "ci", "trace", "environment", "parallel"],
    exp: B("Page object, fixtures, config theo môi trường, chạy CI song song, bật trace để debug.", "Page objects, fixtures, per-environment config, parallel CI runs, trace for debugging.", "ページオブジェクト、フィクスチャ、環境ごとの設定、CIでの並列実行、デバッグ用のトレースを用います。") },
  { cat: "iv-ai", q: B("Bạn dùng AI để tăng năng suất QA như thế nào?", "How do you use AI to boost QA productivity?", "QAの生産性を高めるためにAIをどう活用しますか？"),
    keywords: ["test case", "data", "prompt", "validate", "review", "context", "documentation"],
    exp: B("Sinh test case/dữ liệu, prompt chuẩn hoá theo context team, luôn review & kiểm chứng output.", "Generate cases/data, standardized prompts with team context, always review & validate output.", "テストケースやデータを生成し、チームのコンテキストに沿って標準化したプロンプトを使い、出力は必ずレビュー・検証します。") },
];

export const SCENARIO = [
  { cat: "iv-manual", q: B("Sát ngày release, bạn phát hiện một lỗi nghiêm trọng ở chức năng thanh toán. Bạn xử lý thế nào?", "Right before release you find a critical bug in checkout. What do you do?", "リリース直前に決済機能で重大なバグを見つけました。どう対応しますか？"),
    keywords: ["risk", "severity", "stakeholder", "communicate", "hotfix", "rollback", "impact", "decision"],
    exp: B("Đánh giá tác động & rủi ro, báo stakeholder ngay, đề xuất hotfix/rollback/hoãn, cùng ra quyết định dựa trên dữ liệu.", "Assess impact & risk, alert stakeholders immediately, propose hotfix/rollback/delay, decide together based on data.", "影響とリスクを評価し、ただちにステークホルダーへ報告し、ホットフィックス・ロールバック・延期を提案し、データに基づいて共同で意思決定します。") },
  { cat: "iv-manual", q: B("Dev nói 'không tái hiện được' bug bạn báo. Bạn làm gì?", "A dev says they 'cannot reproduce' your bug. What do you do?", "開発者があなたの報告したバグを「再現できない」と言っています。どうしますか？"),
    keywords: ["environment", "steps", "video", "log", "build version", "data", "pair"],
    exp: B("Xác nhận môi trường/build, cung cấp video + log + dữ liệu chính xác, ngồi cùng dev tái hiện (pair).", "Confirm environment/build, provide video + logs + exact data, pair with the dev to reproduce.", "環境やビルドを確認し、動画・ログ・正確なデータを提供し、開発者と一緒に（ペアで）再現を試みます。") },
  { cat: "iv-automation", q: B("Bộ test E2E của team chạy 45 phút và hay đỏ ngẫu nhiên khiến team mất niềm tin. Bạn cải thiện ra sao?", "Your E2E suite runs 45 min and randomly goes red, eroding trust. How do you improve it?", "チームのE2Eテストは45分かかり、ランダムに失敗して信頼を損ねています。どう改善しますか？"),
    keywords: ["parallel", "shard", "flaky", "wait", "api", "pyramid", "isolate", "stable"],
    exp: B("Chạy song song/shard để giảm thời gian, sửa flaky bằng chờ điều kiện & cô lập dữ liệu, đẩy bớt xuống tầng API theo kim tự tháp.", "Parallelize/shard to cut time, fix flakiness with condition waits & data isolation, push checks down to API per the pyramid.", "並列化・シャーディングで時間を短縮し、条件ベースの待機とデータ隔離でフレーキーさを解消し、ピラミッドに従って検証をAPI層へ移します。") },
  { cat: "iv-ai", q: B("Sếp muốn dùng AI agent tự test toàn bộ sản phẩm. Bạn tư vấn cách triển khai an toàn thế nào?", "Your boss wants an AI agent to auto-test the whole product. How do you advise a safe rollout?", "上司が製品全体をAIエージェントで自動テストしたいと考えています。安全な導入方法をどう助言しますか？"),
    keywords: ["staging", "scope", "least privilege", "human-in-the-loop", "destructive", "review", "boundaries"],
    exp: B("Chạy trong staging cô lập, giới hạn phạm vi & quyền tối thiểu, chặn hành động phá huỷ, giữ human-in-the-loop duyệt kết quả.", "Run in isolated staging, limit scope & least privilege, block destructive actions, keep a human-in-the-loop to approve results.", "隔離されたステージングで実行し、スコープと権限を最小限に絞り、破壊的な操作を禁止し、結果を承認する人間（human-in-the-loop）を残します。") },
];
