import { B } from "./content.mjs";
const O = (vi, en, ja) => ({ vi, en, ja: ja ?? en });

// Additional REAL interview questions (grounded in VN + international sources
// and QA expertise). cat = interview category slug.

export const MCQ2 = [
  // ---- Manual / fundamentals (ISTQB-style) ----
  { cat: "iv-manual", q: B("Verification khác Validation thế nào?", "How does Verification differ from Validation?", "検証（Verification）と妥当性確認（Validation）はどう違いますか？"),
    options: [O("Verification: 'xây đúng sản phẩm', Validation: 'xây sản phẩm đúng'", "Verification: 'build the product right', Validation: 'build the right product'", "検証は「製品を正しく作る」、妥当性確認は「正しい製品を作る」"),
      O("Chúng giống nhau", "They are the same", "両者は同じである"), O("Validation làm trước Verification", "Validation comes before Verification", "妥当性確認が検証より先に行われる"), O("Chỉ Verification cần tài liệu", "Only Verification needs docs", "検証だけがドキュメントを必要とする")],
    answer: 0, exp: B("Verification kiểm tra làm đúng quy trình/đặc tả; Validation kiểm tra sản phẩm đáp ứng nhu cầu người dùng.", "Verification checks we build per spec/process; Validation checks the product meets user needs.", "検証は仕様・プロセス通りに作られているかを確認し、妥当性確認は製品がユーザーのニーズを満たすかを確認します。") },
  { cat: "iv-manual", q: B("STLC (Software Testing Life Cycle) bắt đầu bằng giai đoạn nào?", "Which phase begins the STLC?", "STLC（ソフトウェアテストライフサイクル）はどのフェーズから始まりますか？"),
    options: [O("Test Execution", "Test Execution", "テスト実行"), O("Requirement Analysis", "Requirement Analysis", "要件分析"), O("Test Closure", "Test Closure", "テスト完了"), O("Defect Retest", "Defect Retest", "欠陥の再テスト")],
    answer: 1, exp: B("STLC bắt đầu bằng phân tích yêu cầu để xác định phạm vi kiểm thử.", "STLC starts with requirement analysis to define test scope.", "STLCは、テスト範囲を定義するための要件分析から始まります。") },
  { cat: "iv-manual", q: B("Retesting khác Regression testing ở điểm nào?", "How does Retesting differ from Regression?", "再テスト（Retesting）とリグレッションテストはどこが違いますか？"),
    options: [O("Retest: kiểm lại đúng bug đã fix; Regression: kiểm chức năng liên quan không bị vỡ", "Retest: verify the fixed bug; Regression: check related features didn't break", "再テストは修正したバグの確認、リグレッションは関連機能が壊れていないかの確認"),
      O("Chúng giống nhau", "They are identical", "両者は同一である"), O("Regression chỉ chạy tay", "Regression is manual only", "リグレッションは手動のみ"), O("Retest không cần bug", "Retest needs no bug", "再テストにはバグが不要")],
    answer: 0, exp: B("Retest xác nhận bug cụ thể đã hết; regression đảm bảo không phát sinh lỗi mới.", "Retest confirms the specific bug is gone; regression ensures no new breakage.", "再テストは特定のバグが解消したことを確認し、リグレッションは新たな不具合が発生していないことを保証します。") },
  { cat: "iv-manual", q: B("Positive testing là gì?", "What is positive testing?", "ポジティブテストとは何ですか？"),
    options: [O("Chỉ nhập dữ liệu sai", "Only invalid data", "無効なデータのみを入力する"), O("Kiểm với dữ liệu hợp lệ để xác nhận hoạt động đúng", "Testing with valid data to confirm correct behavior", "有効なデータでテストし、正しく動作することを確認する"),
      O("Test hiệu năng", "Performance testing", "性能テスト"), O("Test bảo mật", "Security testing", "セキュリティテスト")],
    answer: 1, exp: B("Positive testing dùng dữ liệu hợp lệ xác nhận luồng chuẩn chạy đúng.", "Positive testing uses valid data to confirm the happy path works.", "ポジティブテストは有効なデータを用いて、正常系（ハッピーパス）が正しく動作することを確認します。") },
  { cat: "iv-manual", q: B("Test plan và test strategy khác nhau ở đâu?", "Test plan vs test strategy — the difference?", "テスト計画（Test plan）とテスト戦略（Test strategy）の違いは？"),
    options: [O("Strategy: định hướng cấp tổ chức; Plan: chi tiết cho một dự án/tính năng", "Strategy: org-level direction; Plan: project/feature-level detail", "戦略は組織レベルの方向性、計画はプロジェクト／機能レベルの詳細"),
      O("Giống hệt nhau", "Exactly the same", "まったく同じ"), O("Plan không có lịch", "A plan has no schedule", "計画にはスケジュールがない"), O("Strategy do tester junior viết", "Strategy is written by junior testers", "戦略はジュニアのテスターが書く")],
    answer: 0, exp: B("Strategy mang tính định hướng chung; test plan cụ thể hoá cho phạm vi dự án.", "Strategy is high-level direction; the test plan operationalizes it for a project.", "戦略は全体的な方向性を示し、テスト計画はそれをプロジェクトの範囲に具体化します。") },
  { cat: "iv-manual", q: B("Yếu tố KHÔNG bắt buộc trong một bug report tốt?", "Which is NOT essential in a good bug report?", "良いバグ報告に必須で「ない」要素はどれですか？"),
    options: [O("Các bước tái hiện", "Reproduction steps", "再現手順"), O("Kết quả thực tế vs mong đợi", "Actual vs expected result", "実際の結果と期待結果"), O("Ý kiến cá nhân về năng lực dev", "Personal opinion about the dev", "開発者の能力に対する個人的な意見"), O("Môi trường & phiên bản build", "Environment & build version", "環境とビルドバージョン")],
    answer: 2, exp: B("Bug report mô tả sự việc khách quan, không phán xét cá nhân.", "A bug report states facts objectively, no personal judgment.", "バグ報告は事実を客観的に記述するものであり、個人的な評価を含めるべきではありません。") },
  { cat: "iv-manual", q: B("Exploratory testing phù hợp nhất khi nào?", "When is exploratory testing most useful?", "探索的テストが最も有効なのはどんなときですか？"),
    options: [O("Khi tài liệu thiếu và cần học nhanh sản phẩm", "When docs are scarce and you must learn the product fast", "ドキュメントが乏しく、製品を素早く理解する必要があるとき"), O("Khi cần chạy 10.000 lần", "When you need 10,000 runs", "1万回実行する必要があるとき"),
      O("Khi đo hiệu năng", "When measuring performance", "性能を測定するとき"), O("Khi không có tester", "When there is no tester", "テスターがいないとき")],
    answer: 0, exp: B("Exploratory mạnh khi vừa học vừa test, phát hiện lỗi ngoài kịch bản.", "Exploratory shines when learning-while-testing and finding off-script bugs.", "探索的テストは、学びながらテストし、シナリオ外のバグを見つける場面で力を発揮します。") },
  { cat: "iv-manual", q: B("Decision Table testing dùng để làm gì?", "What is decision table testing for?", "デシジョンテーブルテストは何のために使いますか？"),
    options: [O("Kiểm tổ hợp điều kiện–hành động phức tạp", "Testing complex condition–action combinations", "複雑な条件と動作の組み合わせをテストする"), O("Đo tốc độ trang", "Measuring page speed", "ページ速度を測定する"),
      O("Test giao diện màu sắc", "Testing UI colors", "UIの色をテストする"), O("Quản lý bug", "Managing bugs", "バグを管理する")],
    answer: 0, exp: B("Decision table bao phủ các tổ hợp business rule một cách hệ thống.", "Decision tables systematically cover business-rule combinations.", "デシジョンテーブルは、ビジネスルールの組み合わせを体系的に網羅します。") },
  // ---- Automation ----
  { cat: "iv-automation", q: B("Ưu điểm chính của data-driven testing?", "Main benefit of data-driven testing?", "データ駆動テストの主な利点は何ですか？"),
    options: [O("Chạy cùng kịch bản với nhiều bộ dữ liệu", "Run the same script with many data sets", "同じスクリプトを複数のデータセットで実行する"), O("Không cần assertion", "No assertions needed", "アサーションが不要になる"),
      O("Bỏ qua ca lỗi", "Skip error cases", "エラーケースを省く"), O("Chỉ dùng cho UI", "UI only", "UI専用")],
    answer: 0, exp: B("Data-driven tách dữ liệu khỏi logic test, tăng độ phủ mà không nhân bản code.", "Data-driven separates data from logic, boosting coverage without duplicating code.", "データ駆動テストはデータをテストロジックから分離し、コードを重複させずにカバレッジを高めます。") },
  { cat: "iv-automation", q: B("Vai trò của Jenkins/GitHub Actions trong automation?", "Role of Jenkins/GitHub Actions in automation?", "自動化におけるJenkins／GitHub Actionsの役割は？"),
    options: [O("Chạy test tự động theo trigger (push/PR/schedule) trong CI", "Run tests automatically on triggers (push/PR/schedule) in CI", "CIでトリガー（push／PR／スケジュール）に応じてテストを自動実行する"),
      O("Viết test thay tester", "Write tests for you", "テスターの代わりにテストを書く"), O("Thiết kế UI", "Design the UI", "UIを設計する"), O("Lưu trữ ảnh", "Store images", "画像を保存する")],
    answer: 0, exp: B("CI tool tự động chạy test và báo kết quả, chặn lỗi trước khi merge/deploy.", "CI tools auto-run tests and report results, blocking bugs before merge/deploy.", "CIツールはテストを自動実行して結果を報告し、マージ／デプロイ前にバグを防ぎます。") },
  { cat: "iv-automation", q: B("Assertion trong test tự động dùng để?", "Assertions in automated tests are used to?", "自動テストにおけるアサーションは何のために使いますか？"),
    options: [O("Xác minh kết quả thực tế khớp mong đợi", "Verify the actual result matches the expected", "実際の結果が期待結果と一致することを検証する"), O("Tăng tốc test", "Speed up tests", "テストを高速化する"),
      O("Chờ element", "Wait for elements", "要素を待つ"), O("Ghi log", "Write logs", "ログを書き込む")],
    answer: 0, exp: B("Không có assertion thì test 'chạy được' nhưng không kiểm chứng điều gì.", "Without assertions a test 'runs' but verifies nothing.", "アサーションがなければ、テストは「実行される」だけで何も検証しません。") },
  { cat: "iv-automation", q: B("Selenium WebDriver KHÔNG hỗ trợ điều nào sau đây natively?", "Which does Selenium WebDriver NOT support natively?", "Selenium WebDriverが標準（ネイティブ）で対応していないのはどれですか？"),
    options: [O("Điều khiển trình duyệt", "Driving browsers", "ブラウザの操作"), O("Quản lý test & report (cần TestNG/JUnit)", "Test management & reporting (needs TestNG/JUnit)", "テスト管理とレポート（TestNG/JUnitが必要）"),
      O("Định vị element", "Locating elements", "要素の特定"), O("Thực thi JavaScript", "Executing JavaScript", "JavaScriptの実行")],
    answer: 1, exp: B("Selenium chỉ điều khiển trình duyệt; báo cáo/quản lý test cần framework như TestNG/JUnit.", "Selenium only drives the browser; reporting/management needs frameworks like TestNG/JUnit.", "Seleniumはブラウザ操作のみを担い、レポートやテスト管理にはTestNG/JUnitなどのフレームワークが必要です。") },
  { cat: "iv-automation", q: B("Kỹ thuật nào giảm phụ thuộc giữa các test?", "Which reduces inter-test dependency?", "テスト間の依存を減らすのはどれですか？"),
    options: [O("Dùng chung state toàn cục", "Sharing global state", "グローバルな状態を共有する"), O("Mỗi test tự setup & teardown dữ liệu riêng", "Each test sets up & tears down its own data", "各テストが自前でデータのセットアップとクリーンアップを行う"),
      O("Chạy tuần tự theo thứ tự cố định", "Run sequentially in fixed order", "固定の順序で逐次実行する"), O("Dùng sleep dài", "Use long sleeps", "長いスリープを使う")],
    answer: 1, exp: B("Test độc lập với dữ liệu riêng giúp chạy song song và ổn định.", "Independent tests with own data enable parallelism and stability.", "自前のデータを持つ独立したテストは、並列実行と安定性を可能にします。") },
  // ---- Playwright ----
  { cat: "iv-playwright", q: B("APIRequestContext trong Playwright dùng để?", "What is Playwright's APIRequestContext for?", "PlaywrightのAPIRequestContextは何のために使いますか？"),
    options: [O("Gửi request API trực tiếp (không qua UI)", "Send API requests directly (without the UI)", "UIを介さずにAPIリクエストを直接送信する"), O("Chụp màn hình", "Take screenshots", "スクリーンショットを撮る"),
      O("Chờ element", "Wait for elements", "要素を待つ"), O("Ghi video", "Record video", "動画を記録する")],
    answer: 0, exp: B("Playwright test được cả API lẫn UI; APIRequestContext gọi API trực tiếp.", "Playwright tests both API and UI; APIRequestContext calls APIs directly.", "PlaywrightはAPIとUIの両方をテストでき、APIRequestContextはAPIを直接呼び出します。") },
  { cat: "iv-playwright", q: B("Fixtures trong Playwright giúp gì?", "What do Playwright fixtures provide?", "Playwrightのフィクスチャは何を提供しますか？"),
    options: [O("Thiết lập/dọn dẹp và chia sẻ ngữ cảnh (page, auth) cho test", "Setup/teardown and share context (page, auth) for tests", "テスト用のセットアップ／クリーンアップと、コンテキスト（page、認証）の共有"),
      O("Tăng độ phân giải màn hình", "Increase screen resolution", "画面解像度を上げる"), O("Tự viết assertion", "Auto-write assertions", "アサーションを自動生成する"), O("Mã hoá dữ liệu", "Encrypt data", "データを暗号化する")],
    answer: 0, exp: B("Fixtures cung cấp tài nguyên đã cấu hình (đăng nhập sẵn, page) cho test một cách sạch.", "Fixtures provide configured resources (pre-auth, page) to tests cleanly.", "フィクスチャは、設定済みのリソース（認証済み状態やpage）をテストにクリーンに提供します。") },
  { cat: "iv-playwright", q: B("Cách xử lý đăng nhập một lần rồi tái dùng trong Playwright?", "How to log in once and reuse it in Playwright?", "Playwrightで一度ログインして再利用するにはどうしますか？"),
    options: [O("Lưu storageState và nạp lại cho các test", "Save storageState and reuse it across tests", "storageStateを保存し、各テストで再利用する"), O("Đăng nhập lại mỗi test", "Log in again every test", "テストごとに毎回ログインし直す"),
      O("Tắt xác thực", "Disable auth", "認証を無効化する"), O("Dùng sleep", "Use sleep", "スリープを使う")],
    answer: 0, exp: B("storageState lưu cookie/localStorage sau khi đăng nhập, tái dùng để test nhanh & ổn định.", "storageState saves cookies/localStorage after login, reused for fast, stable tests.", "storageStateはログイン後のCookieやlocalStorageを保存し、それを再利用することで高速で安定したテストを実現します。") },
  { cat: "iv-playwright", q: B("Trace viewer của Playwright hữu ích nhất khi nào?", "When is Playwright's trace viewer most useful?", "Playwrightのトレースビューアが最も役立つのはどんなときですか？"),
    options: [O("Điều tra test fail trong CI theo từng bước + DOM", "Investigating CI failures step-by-step with DOM", "CIでの失敗をステップごとにDOMとともに調査するとき"), O("Tăng tốc test", "Speeding up tests", "テストを高速化するとき"),
      O("Viết test mới", "Writing new tests", "新しいテストを書くとき"), O("Quản lý bug", "Managing bugs", "バグを管理するとき")],
    answer: 0, exp: B("Trace ghi lại từng bước, ảnh, network để debug fail mà không cần tái hiện tay.", "Traces record each step, snapshots and network to debug failures without manual repro.", "トレースは各ステップ・スナップショット・ネットワークを記録し、手動で再現しなくても失敗をデバッグできます。") },
  // ---- AI ----
  { cat: "iv-ai", q: B("Prompt engineering trong QA giúp ích nhất ở đâu?", "Where does prompt engineering help QA most?", "QAにおいてプロンプトエンジニアリングが最も役立つのはどこですか？"),
    options: [O("Sinh test case/dữ liệu & tóm tắt log nhanh, nhất quán", "Fast, consistent test-case/data generation & log summarization", "テストケース／データ生成やログ要約を、速く一貫して行うこと"),
      O("Thay thế hoàn toàn tester", "Fully replacing testers", "テスターを完全に置き換えること"), O("Tự triển khai production", "Auto-deploying to production", "本番へ自動デプロイすること"), O("Đảm bảo 0 lỗi", "Guaranteeing zero bugs", "バグゼロを保証すること")],
    answer: 0, exp: B("AI hỗ trợ thiết kế & tài liệu; con người vẫn kiểm chứng và quyết định.", "AI assists design & docs; humans still validate and decide.", "AIは設計やドキュメント作成を支援しますが、検証と意思決定は依然として人間が行います。") },
  { cat: "iv-ai", q: B("Khi để AI agent test app, biện pháp an toàn quan trọng nhất là?", "The most important safety measure when an AI agent tests an app?", "AIエージェントにアプリをテストさせる際、最も重要な安全対策は？"),
    options: [O("Chạy trong staging cô lập + human-in-the-loop", "Run in isolated staging + human-in-the-loop", "隔離されたステージングで実行し、人間を介在（human-in-the-loop）させる"), O("Cấp full quyền production", "Grant full production access", "本番への全権限を与える"),
      O("Bỏ review", "Skip review", "レビューを省く"), O("Cho xoá dữ liệu tự do", "Allow free data deletion", "自由なデータ削除を許可する")],
    answer: 0, exp: B("Cô lập môi trường, quyền tối thiểu và người giám sát là nguyên tắc cốt lõi.", "Isolated environment, least privilege and human oversight are the core principles.", "環境の隔離、最小権限、人間による監督が中核となる原則です。") },
];

export const ESSAY2 = [
  { cat: "iv-manual", q: B("Giải thích sự khác nhau giữa SDLC và STLC.", "Explain the difference between SDLC and STLC.", "SDLCとSTLCの違いを説明してください。"),
    keywords: ["development", "testing", "life cycle", "requirement", "design", "phase", "parallel"],
    exp: B("SDLC là vòng đời phát triển phần mềm; STLC là vòng đời kiểm thử nằm trong đó, chạy song song với các pha phát triển.", "SDLC is the software development life cycle; STLC is the testing life cycle within it, running in parallel with development phases.", "SDLCはソフトウェア開発ライフサイクルであり、STLCはその中にあるテストのライフサイクルで、開発の各フェーズと並行して進みます。") },
  { cat: "iv-manual", q: B("Bạn ưu tiên test cái gì khi thời gian rất hạn chế?", "What do you prioritize testing when time is very limited?", "時間が非常に限られているとき、何を優先してテストしますか？"),
    keywords: ["risk", "critical", "core", "smoke", "impact", "business", "high priority"],
    exp: B("Ưu tiên theo rủi ro & tác động: luồng nghiệp vụ cốt lõi, chức năng rủi ro cao, smoke test trước.", "Prioritize by risk & impact: core business flows, high-risk features, smoke first.", "リスクと影響度で優先します。中核となる業務フロー、リスクの高い機能、まずはスモークテストを行います。") },
  { cat: "iv-manual", q: B("Mô tả quy trình testing bạn thường áp dụng trong một sprint.", "Describe your usual testing process within a sprint.", "スプリント内で普段行っているテストのプロセスを説明してください。"),
    keywords: ["requirement", "test case", "execution", "bug", "retest", "regression", "report"],
    exp: B("Phân tích yêu cầu → thiết kế test case → thực thi → log bug → retest → regression → báo cáo.", "Analyze requirements → design cases → execute → log bugs → retest → regression → report.", "要件分析 → テストケース設計 → 実行 → バグ記録 → 再テスト → リグレッション → 報告、の順で進めます。") },
  { cat: "iv-automation", q: B("Bạn thiết kế kiến trúc một framework automation từ đầu như thế nào?", "How would you architect an automation framework from scratch?", "自動化フレームワークをゼロからどのように設計しますか？"),
    keywords: ["page object", "config", "data-driven", "reporting", "ci", "utilities", "environment"],
    exp: B("Tách page object, cấu hình theo môi trường, data-driven, tiện ích chung, report và tích hợp CI.", "Separate page objects, per-env config, data-driven data, shared utilities, reporting and CI integration.", "ページオブジェクトの分離、環境ごとの設定、データ駆動、共通ユーティリティ、レポート、CI連携を用いて構成します。") },
  { cat: "iv-automation", q: B("Bạn tích hợp API testing vào pipeline CI ra sao?", "How do you integrate API testing into a CI pipeline?", "APIテストをCIパイプラインにどのように組み込みますか？"),
    keywords: ["collection", "newman", "assertion", "schema", "stage", "report", "fail"],
    exp: B("Chạy collection (Newman) hoặc test API ở một stage CI, assert status/schema, fail pipeline khi lỗi, xuất report.", "Run a collection (Newman) or API tests as a CI stage, assert status/schema, fail the pipeline on error, publish a report.", "コレクション（Newman）やAPIテストをCIの1ステージとして実行し、ステータスやスキーマを検証し、エラー時はパイプラインを失敗させ、レポートを出力します。") },
  { cat: "iv-playwright", q: B("So sánh Playwright và Selenium: khi nào chọn cái nào?", "Compare Playwright and Selenium: when choose which?", "PlaywrightとSeleniumを比較し、どんなときにどちらを選びますか？"),
    keywords: ["auto-wait", "trace", "cross-browser", "legacy", "grid", "speed", "greenfield"],
    exp: B("Playwright cho dự án mới (auto-wait, trace, tốc độ); Selenium khi cần hệ sinh thái/grid lâu đời hoặc stack legacy.", "Playwright for greenfield (auto-wait, trace, speed); Selenium for mature grid ecosystems or legacy stacks.", "新規プロジェクトにはPlaywright（自動待機、トレース、速度）を、成熟したグリッド環境やレガシースタックにはSeleniumを選びます。") },
  { cat: "iv-ai", q: B("Rủi ro và cách kiểm soát khi dùng LLM trong quy trình QA?", "Risks and controls when using LLMs in QA?", "QAプロセスでLLMを使う際のリスクとその管理策は？"),
    keywords: ["hallucination", "validate", "privacy", "pii", "review", "bias", "context"],
    exp: B("Rủi ro ảo giác, rò rỉ dữ liệu, thiên lệch; kiểm soát bằng review, không đưa PII, cung cấp context và luôn xác minh.", "Risks: hallucination, data leakage, bias; controls: review, no PII, provide context, always validate.", "リスクはハルシネーション、データ漏洩、バイアスです。管理策として、レビューを行い、PIIを入力せず、コンテキストを与え、常に検証します。") },
];

export const SCENARIO2 = [
  { cat: "iv-automation", q: B("Một test tự động fail trong CI nhưng chạy tay lại pass. Bạn điều tra thế nào?", "An automated test fails in CI but passes locally. How do you investigate?", "自動テストがCIでは失敗するのにローカルでは成功します。どう調査しますか？"),
    keywords: ["environment", "timing", "data", "trace", "log", "headless", "parallel", "isolate"],
    exp: B("So sánh môi trường (headless, độ trễ, dữ liệu), xem trace/log CI, kiểm timing & tính song song, cô lập nguyên nhân.", "Compare environment (headless, latency, data), read CI trace/logs, check timing & parallelism, isolate the cause.", "環境（ヘッドレス、遅延、データ）を比較し、CIのトレースやログを確認し、タイミングと並列性を調べ、原因を切り分けます。") },
  { cat: "iv-manual", q: B("PM yêu cầu bỏ qua test để kịp deadline. Bạn phản hồi thế nào?", "The PM asks to skip testing to hit a deadline. How do you respond?", "PMが締め切りに間に合わせるためテストを省くよう求めています。どう対応しますか？"),
    keywords: ["risk", "impact", "communicate", "prioritize", "smoke", "decision", "transparent"],
    exp: B("Trình bày rủi ro rõ ràng bằng dữ liệu, đề xuất test theo rủi ro (smoke/critical), để quyết định minh bạch cùng stakeholder.", "Present risks clearly with data, propose risk-based testing (smoke/critical), and make a transparent decision with stakeholders.", "リスクをデータで明確に示し、リスクベースのテスト（スモーク／重要機能）を提案し、ステークホルダーと透明性のある意思決定を行います。") },
  { cat: "iv-manual", q: B("Khách báo lỗi chỉ xảy ra trên máy họ, bạn không tái hiện được. Xử lý?", "A customer reports a bug only on their machine you can't reproduce. What do you do?", "顧客の端末でのみ発生し再現できないバグが報告されました。どう対応しますか？"),
    keywords: ["environment", "browser", "version", "log", "data", "network", "remote", "screenshot"],
    exp: B("Thu thập môi trường/trình duyệt/phiên bản, log & network, dữ liệu cụ thể, hỗ trợ từ xa hoặc video để tái hiện.", "Collect environment/browser/version, logs & network, exact data, use remote support or video to reproduce.", "環境・ブラウザ・バージョン、ログやネットワーク、具体的なデータを収集し、リモートサポートや動画で再現を試みます。") },
  { cat: "iv-playwright", q: B("Bộ E2E Playwright chạy chậm và tốn phút CI. Bạn tối ưu ra sao?", "Your Playwright E2E suite is slow and burns CI minutes. How do you optimize?", "PlaywrightのE2Eスイートが遅くCI時間を消費しています。どう最適化しますか？"),
    keywords: ["parallel", "shard", "reuse auth", "api setup", "trace on-failure", "select", "pyramid"],
    exp: B("Chạy song song & shard, tái dùng storageState, setup dữ liệu qua API thay vì UI, chỉ bật trace khi fail, đẩy kiểm tra xuống API.", "Parallelize & shard, reuse storageState, seed data via API instead of UI, trace only on failure, push checks down to API.", "並列化とシャーディングを行い、storageStateを再利用し、データをUIではなくAPIで準備し、失敗時のみトレースを有効化し、検証をAPI層へ移します。") },
  { cat: "iv-ai", q: B("Team muốn dùng AI tự sinh toàn bộ test case. Bạn đề xuất quy trình kiểm soát chất lượng nào?", "The team wants AI to auto-generate all test cases. What QA control process do you propose?", "チームがすべてのテストケースをAIで自動生成したいと考えています。どんな品質管理プロセスを提案しますか？"),
    keywords: ["review", "validate", "coverage", "requirement", "human", "edge case", "iterate"],
    exp: B("AI sinh nháp, con người review đối chiếu requirement & độ phủ, bổ sung ca biên domain, lặp lại và chuẩn hoá prompt.", "AI drafts, humans review against requirements & coverage, add domain edge cases, iterate and standardize prompts.", "AIが下書きを生成し、人間が要件とカバレッジに照らしてレビューし、ドメイン固有の境界ケースを追加し、反復しながらプロンプトを標準化します。") },
];
