// Additional REAL topics — compact authoring format expanded by buildPages().
const S = (vi, en) => ({ vi, en, ja: en });
function T(t) {
  const o = {
    title: S(t.tv, t.te), summary: S(t.sv, t.se), objective: S(t.ov, t.oe), concept: S(t.cv, t.ce),
    steps: (t.st || []).map(([vi, en]) => S(vi, en)),
    checklist: (t.ck || []).map(([vi, en]) => S(vi, en)),
  };
  if (t.av) o.aiTip = S(t.av, t.ae);
  if (t.pf) o.pitfalls = t.pf.map(([vi, en]) => S(vi, en));
  if (t.exv) o.example = { vi: t.exv, en: t.exe, code: t.code };
  return o;
}

// ---------------- NEW CATEGORY: AUTOMATION TOOLS ----------------
export const NEW_CATEGORIES = [
  {
    slug: "automation-tools", title: S("Công cụ Automation Testing", "Automation Testing Tools"), icon: "🧰",
    topics: [
      T({ tv:"Selenium WebDriver toàn tập", te:"Selenium WebDriver essentials",
        sv:"Điều khiển trình duyệt đa nền tảng, đa ngôn ngữ — nền tảng automation kinh điển.", se:"Cross-browser, multi-language browser automation — the classic foundation.",
        ov:"Hiểu kiến trúc Selenium và viết test ổn định với waits & POM.", oe:"Understand Selenium's architecture and write stable tests with waits & POM.",
        cv:"Selenium WebDriver điều khiển trình duyệt qua W3C protocol, hỗ trợ Java/C#/Python/JS. Cần framework (TestNG/JUnit/pytest) để quản lý & report.", ce:"Selenium WebDriver drives browsers via the W3C protocol, supporting Java/C#/Python/JS. It needs a framework (TestNG/JUnit/pytest) for management & reporting.",
        st:[["Chọn ngôn ngữ + framework runner","Pick a language + framework runner"],["Dùng explicit wait thay implicit/sleep","Use explicit waits over implicit/sleep"],["Áp dụng Page Object Model","Apply the Page Object Model"],["Chạy trên Selenium Grid để song song","Run on Selenium Grid for parallelism"]],
        ck:[["Dùng explicit wait","Use explicit waits"],["Locator ổn định (id/css/testid)","Stable locators (id/css/testid)"]],
        av:"Nhờ AI chuyển các bước tay thành script Selenium khung POM rồi bạn tinh chỉnh.", ae:"Ask AI to turn manual steps into a POM-structured Selenium script, then refine." }),
      T({ tv:"Cypress cho test frontend hiện đại", te:"Cypress for modern frontend testing",
        sv:"Chạy trong trình duyệt, time-travel debug, tự chờ — mạnh cho SPA.", se:"Runs in-browser, time-travel debugging, auto-wait — great for SPAs.",
        ov:"Viết E2E/component test bằng Cypress và hiểu giới hạn của nó.", oe:"Write E2E/component tests with Cypress and understand its limits.",
        cv:"Cypress chạy cùng ngữ cảnh trình duyệt, có auto-wait, snapshot và debug trực quan. Hạn chế: đa tab/đa domain và chỉ JS/TS.", ce:"Cypress runs in the browser context with auto-wait, snapshots and visual debugging. Limits: multi-tab/multi-domain and JS/TS only.",
        st:[["cypress open để chạy interactive","cypress open for interactive runs"],["Dùng cy.intercept mock API","Use cy.intercept to mock APIs"],["Tổ chức custom commands tái dùng","Organize reusable custom commands"],["Tích hợp CI headless","Integrate headless CI"]],
        ck:[["Mock API để test ổn định","Mock APIs for stable tests"],["Tránh phụ thuộc thứ tự","Avoid order dependency"]] }),
      T({ tv:"Appium — automation mobile Android/iOS", te:"Appium — mobile automation for Android/iOS",
        sv:"Một API test cả native, hybrid và web trên di động.", se:"One API to test native, hybrid and mobile web.",
        ov:"Thiết lập Appium và chạy test đầu tiên trên emulator/thiết bị thật.", oe:"Set up Appium and run a first test on an emulator/real device.",
        cv:"Appium dùng WebDriver protocol điều khiển app di động, hỗ trợ nhiều ngôn ngữ, chạy trên emulator & device farm.", ce:"Appium uses the WebDriver protocol to drive mobile apps, supports many languages, runs on emulators & device farms.",
        st:[["Cài Appium + driver (UiAutomator2/XCUITest)","Install Appium + driver (UiAutomator2/XCUITest)"],["Khai báo desired capabilities","Declare desired capabilities"],["Định vị element bằng accessibility id","Locate elements by accessibility id"],["Chạy trên cloud device (BrowserStack/Sauce)","Run on cloud devices (BrowserStack/Sauce)"]],
        ck:[["Ưu tiên accessibility id","Prefer accessibility id"],["Test trên nhiều độ phân giải","Test multiple resolutions"]] }),
      T({ tv:"Postman & Newman cho API automation", te:"Postman & Newman for API automation",
        sv:"Từ test tay tới chạy collection tự động trong CI.", se:"From manual tests to automated collection runs in CI.",
        ov:"Xây collection có test script và chạy tự động bằng Newman.", oe:"Build a scripted collection and run it automatically with Newman.",
        cv:"Postman quản lý request + test script (chai); Newman chạy collection trên CLI/CI, xuất report.", ce:"Postman manages requests + test scripts (chai); Newman runs collections on CLI/CI with reports.",
        st:[["Nhóm request theo folder & môi trường","Group requests by folder & environment"],["Viết test script assert status/schema","Write test scripts asserting status/schema"],["Dùng biến & pre-request script","Use variables & pre-request scripts"],["Chạy newman trong pipeline","Run newman in the pipeline"]],
        ck:[["Assert cả status lẫn schema","Assert both status and schema"],["Tách môi trường dev/stg/prod","Separate dev/stg/prod environments"]] }),
      T({ tv:"REST Assured — API test trong Java", te:"REST Assured — API testing in Java",
        sv:"DSL gọn cho given/when/then khi test REST trong hệ sinh thái Java.", se:"A concise given/when/then DSL for REST testing in the Java ecosystem.",
        ov:"Viết test API dễ đọc và tích hợp vào bộ test Java/TestNG.", oe:"Write readable API tests integrated into a Java/TestNG suite.",
        cv:"REST Assured cung cấp cú pháp BDD-style, hỗ trợ JSONPath/schema validation, xác thực & serialization.", ce:"REST Assured offers BDD-style syntax with JSONPath/schema validation, auth & serialization.",
        st:[["given().header().when().get().then()","given().header().when().get().then()"],["Validate JSONPath & schema","Validate JSONPath & schema"],["Tách base config & auth","Separate base config & auth"],["Tích hợp report Allure","Integrate Allure reporting"]],
        ck:[["Có schema validation","Has schema validation"],["Ca lỗi & phân quyền","Error & authz cases"]] }),
      T({ tv:"JMeter — kiểm thử tải kinh điển", te:"JMeter — classic load testing",
        sv:"GUI mạnh cho load/stress test HTTP, JDBC, JMS.", se:"A powerful GUI for HTTP, JDBC, JMS load/stress testing.",
        ov:"Dựng test plan JMeter và đọc kết quả throughput/latency.", oe:"Build a JMeter test plan and read throughput/latency results.",
        cv:"JMeter mô phỏng nhiều thread (user) gửi request, đo response time, throughput, error; chạy được phân tán.", ce:"JMeter simulates many threads (users) sending requests, measuring response time, throughput, errors; supports distributed runs.",
        st:[["Thiết lập Thread Group (users/ramp-up)","Set Thread Group (users/ramp-up)"],["Thêm Samplers & Assertions","Add Samplers & Assertions"],["Dùng Listeners xem kết quả","Use Listeners to view results"],["Chạy non-GUI cho tải lớn","Run non-GUI for heavy load"]],
        ck:[["Chạy non-GUI khi tải cao","Non-GUI for high load"],["Xem p95/p99, không chỉ trung bình","Check p95/p99, not just average"]] }),
      T({ tv:"Jenkins & pipeline CI cho test", te:"Jenkins & CI pipelines for testing",
        sv:"Tự động hoá build–test–report với Jenkinsfile.", se:"Automate build–test–report with a Jenkinsfile.",
        ov:"Cấu hình pipeline chạy test tự động và công bố report.", oe:"Configure a pipeline to run tests automatically and publish reports.",
        cv:"Jenkins điều phối job qua Jenkinsfile (declarative), tích hợp SCM, chạy test theo trigger, lưu artifact & report.", ce:"Jenkins orchestrates jobs via a (declarative) Jenkinsfile, integrates SCM, runs tests on triggers, stores artifacts & reports.",
        st:[["Viết stages: build → test → report","Write stages: build → test → report"],["Trigger theo webhook/schedule","Trigger by webhook/schedule"],["Publish HTML/Allure report","Publish HTML/Allure reports"],["Đặt quality gate fail pipeline","Set a quality gate to fail the pipeline"]],
        ck:[["Test chạy tự động mỗi commit","Tests run on each commit"],["Report công khai cho team","Reports visible to the team"]] }),
      T({ tv:"Docker cho môi trường test nhất quán", te:"Docker for consistent test environments",
        sv:"'Chạy được trên máy tôi' — Docker xoá bỏ khác biệt môi trường.", se:"'Works on my machine' — Docker removes environment drift.",
        ov:"Đóng gói ứng dụng & test vào container để chạy giống nhau mọi nơi.", oe:"Package app & tests into containers to run identically everywhere.",
        cv:"Docker đóng gói phụ thuộc thành image; docker-compose dựng nhiều dịch vụ (app+db) cho E2E ổn định trong CI.", ce:"Docker packages dependencies into images; docker-compose spins up multiple services (app+db) for stable E2E in CI.",
        st:[["Viết Dockerfile cho test runner","Write a Dockerfile for the test runner"],["docker-compose dựng app+db","docker-compose for app+db"],["Chạy test trong container ở CI","Run tests in a container in CI"],["Dọn dữ liệu bằng container tạm","Reset data via ephemeral containers"]],
        ck:[["Môi trường tái lập 100%","100% reproducible env"],["Dữ liệu sạch mỗi lần chạy","Clean data per run"]] }),
      T({ tv:"BDD với Cucumber/Gherkin", te:"BDD with Cucumber/Gherkin",
        sv:"Given–When–Then giúp business & QA cùng hiểu test.", se:"Given–When–Then lets business & QA share understanding.",
        ov:"Viết kịch bản Gherkin và nối với step definitions.", oe:"Write Gherkin scenarios and bind them to step definitions.",
        cv:"BDD mô tả hành vi bằng ngôn ngữ tự nhiên (feature files), gắn với code qua step definitions — tăng cộng tác.", ce:"BDD describes behavior in natural language (feature files) bound to code via step definitions — boosting collaboration.",
        st:[["Viết feature Given/When/Then","Write Given/When/Then features"],["Cài đặt step definitions","Implement step definitions"],["Tái dùng step & tham số hoá","Reuse & parameterize steps"],["Sinh report living documentation","Generate living-documentation reports"]],
        ck:[["Scenario dễ đọc cho business","Business-readable scenarios"],["Step tái dùng, không trùng","Reusable, non-duplicated steps"]] }),
      T({ tv:"Allure & báo cáo kết quả test", te:"Allure & test result reporting",
        sv:"Report trực quan: bước, ảnh, xu hướng, phân loại lỗi.", se:"Visual reports: steps, screenshots, trends, defect categories.",
        ov:"Tích hợp Allure để báo cáo đẹp, dễ điều tra fail.", oe:"Integrate Allure for rich reports that ease failure triage.",
        cv:"Allure gom kết quả từ nhiều framework, hiển thị step, attachment, severity & xu hướng theo thời gian.", ce:"Allure aggregates results across frameworks, showing steps, attachments, severity & trends over time.",
        st:[["Thêm adapter cho framework","Add the framework adapter"],["Đính ảnh/log vào step","Attach screenshots/logs to steps"],["Gắn severity & tag","Tag severity & labels"],["Publish trên CI","Publish on CI"]],
        ck:[["Report có ảnh khi fail","Reports include failure screenshots"],["Theo dõi xu hướng pass/fail","Track pass/fail trends"]] }),
    ],
  },
  // ---------------- NEW CATEGORY: AI INTEGRATION IN TESTING ----------------
  {
    slug: "ai-integration", title: S("Tích hợp AI vào Testing", "Integrating AI into Testing"), icon: "🔗",
    topics: [
      T({ tv:"Nhúng AI vào pipeline kiểm thử", te:"Embedding AI into the test pipeline",
        sv:"Từ sinh test tới phân tích fail — AI ở mỗi khâu.", se:"From test generation to failure analysis — AI at each stage.",
        ov:"Xác định điểm chèn AI hiệu quả trong quy trình QA.", oe:"Identify effective AI insertion points across the QA process.",
        cv:"AI có thể hỗ trợ: sinh test case, tạo dữ liệu, phân loại lỗi CI, tóm tắt log, đề xuất ưu tiên regression — luôn có người kiểm chứng.", ce:"AI can assist: test generation, data creation, CI failure triage, log summarization, regression prioritization — always human-validated.",
        st:[["Lập bản đồ quy trình QA hiện tại","Map the current QA process"],["Chọn khâu ROI cao để thử AI","Pick high-ROI stages to pilot AI"],["Đặt quy tắc kiểm chứng đầu ra","Set output validation rules"],["Đo tác động & mở rộng","Measure impact & scale"]],
        ck:[["Có bước người kiểm chứng","Human validation step exists"],["Không đưa dữ liệu nhạy cảm","No sensitive data shared"]],
        av:"Bắt đầu với 1 khâu (VD phân loại fail CI) để chứng minh giá trị trước khi mở rộng.", ae:"Start with one stage (e.g. CI failure triage) to prove value before scaling." }),
      T({ tv:"AI sinh dữ liệu test thực tế & ẩn danh", te:"AI-generated realistic, anonymized test data",
        sv:"Tạo dữ liệu đa dạng, hợp lệ mà không lộ PII.", se:"Create diverse valid data without leaking PII.",
        ov:"Dùng AI tạo bộ dữ liệu biên & ẩn danh cho test.", oe:"Use AI to produce edge & anonymized datasets for testing.",
        cv:"LLM sinh dữ liệu giả nhưng thực tế (tên, địa chỉ, giao dịch) theo ràng buộc; kết hợp masking cho dữ liệu production.", ce:"LLMs generate realistic fake data (names, addresses, transactions) under constraints; combine with masking for production data.",
        st:[["Mô tả ràng buộc & định dạng dữ liệu","Describe data constraints & formats"],["Yêu cầu ca biên & không hợp lệ","Request edge & invalid cases"],["Ẩn danh dữ liệu thật (masking)","Anonymize real data (masking)"],["Kiểm tính hợp lệ trước khi dùng","Validate before use"]],
        ck:[["Dữ liệu đa dạng, có ca biên","Diverse data with edge cases"],["Không chứa PII thật","No real PII"]] }),
      T({ tv:"Self-healing locator bằng AI", te:"AI self-healing locators",
        sv:"Giảm test vỡ khi UI đổi nhờ AI đoán locator thay thế.", se:"Reduce breakage on UI change via AI-suggested locators.",
        ov:"Hiểu cơ chế & giới hạn của self-healing trong công cụ hiện đại.", oe:"Understand the mechanism & limits of self-healing in modern tools.",
        cv:"Công cụ (Testim, Mabl, Healenium) lưu nhiều thuộc tính element; khi locator chính hỏng, AI chọn ứng viên gần nhất — cần review để tránh 'chữa sai'.", ce:"Tools (Testim, Mabl, Healenium) store multiple element attributes; when the main locator breaks, AI picks the closest candidate — review to avoid 'healing wrong'.",
        st:[["Bật self-healing trong công cụ","Enable self-healing in the tool"],["Xem log healing mỗi lần chạy","Review healing logs each run"],["Xác nhận thay đổi hợp lệ","Confirm valid changes"],["Cập nhật locator chuẩn định kỳ","Periodically update canonical locators"]],
        ck:[["Review log healing","Review healing logs"],["Không tin tuyệt đối","Don't fully trust it"]] }),
      T({ tv:"Visual testing với AI (Applitools/Percy)", te:"AI visual testing (Applitools/Percy)",
        sv:"So sánh ảnh thông minh, bỏ qua nhiễu, bắt lỗi giao diện.", se:"Smart image diffing that ignores noise and catches UI defects.",
        ov:"Thiết lập baseline & quy trình duyệt cho visual testing.", oe:"Set up baselines & an approval flow for visual testing.",
        cv:"AI visual so sánh theo nhận thức người dùng (bỏ qua khác biệt vô nghĩa), phát hiện lệch layout/màu/chữ.", ce:"AI visual compares perceptually (ignoring meaningless diffs), catching layout/color/text shifts.",
        st:[["Chụp baseline các màn hình chính","Snapshot baselines of key screens"],["Ổn định dữ liệu động trước khi chụp","Stabilize dynamic data first"],["Duyệt diff hợp lệ để cập nhật baseline","Approve valid diffs to update baseline"],["Tích hợp CI chặn thay đổi bất ngờ","Integrate CI to block unexpected changes"]],
        ck:[["Đã ổn định dữ liệu động","Stabilized dynamic data"],["Quy trình duyệt baseline rõ","Clear baseline approval"]] }),
      T({ tv:"AI phân loại & điều tra fail trong CI", te:"AI triage & investigation of CI failures",
        sv:"Phân biệt lỗi thật vs flaky vs môi trường, tăng tốc điều tra.", se:"Separate real vs flaky vs environment failures, speeding triage.",
        ov:"Dùng AI đọc log/trace để phân loại nguyên nhân fail.", oe:"Use AI to read logs/traces and classify failure causes.",
        cv:"AI tóm tắt log, gom nhóm fail giống nhau, gợi ý nguyên nhân — giảm thời gian tester đào log thủ công.", ce:"AI summarizes logs, clusters similar failures, suggests causes — cutting manual log-digging time.",
        st:[["Đưa log/trace fail cho AI tóm tắt","Feed failure logs/traces to AI"],["Phân loại: code/flaky/môi trường/dữ liệu","Classify: code/flaky/env/data"],["Ưu tiên xử lý theo nhóm","Prioritize by cluster"],["Ghi nhận để giảm lặp lại","Record to reduce recurrence"]],
        ck:[["Phân loại đúng nhóm fail","Correct failure classification"],["Giảm thời gian điều tra","Reduced triage time"]] }),
      T({ tv:"Ưu tiên regression theo rủi ro bằng AI", te:"AI risk-based regression prioritization",
        sv:"Chạy test có khả năng bắt lỗi cao trước khi hết thời gian.", se:"Run the most defect-likely tests first before time runs out.",
        ov:"Dùng lịch sử thay đổi & lỗi để AI xếp thứ tự test.", oe:"Use change & defect history for AI to order tests.",
        cv:"AI phân tích code thay đổi, lịch sử lỗi & tần suất để chọn tập test tối ưu (test impact analysis).", ce:"AI analyzes changed code, defect history & frequency to select an optimal test subset (test impact analysis).",
        st:[["Thu thập lịch sử thay đổi & fail","Collect change & failure history"],["Cho AI xếp hạng test theo rủi ro","Have AI rank tests by risk"],["Chạy tập rủi ro cao trong smoke","Run the high-risk subset as smoke"],["Đo tỉ lệ bắt lỗi sớm","Measure early defect detection"]],
        ck:[["Tập test gắn với thay đổi","Test subset tied to changes"],["Đo hiệu quả ưu tiên","Measure prioritization effect"]] }),
      T({ tv:"Thư viện prompt chuẩn cho team QA", te:"A standard prompt library for QA teams",
        sv:"Chuẩn hoá cách dùng AI để kết quả nhất quán, chất lượng.", se:"Standardize AI usage for consistent, quality output.",
        ov:"Xây bộ prompt tái dùng gắn với chuẩn công ty.", oe:"Build reusable prompts aligned to company standards.",
        cv:"Prompt library gồm mẫu cho: sinh test case, review bug, tóm tắt log, sinh dữ liệu — kèm ràng buộc & ví dụ few-shot.", ce:"A prompt library includes templates for: test-case gen, bug review, log summary, data gen — with constraints & few-shot examples.",
        st:[["Thu thập use case AI phổ biến của team","Collect the team's common AI use cases"],["Chuẩn hoá prompt + ví dụ mẫu","Standardize prompts + samples"],["Lưu & version hoá prompt","Store & version the prompts"],["Đo & cải tiến theo phản hồi","Measure & refine from feedback"]],
        ck:[["Prompt có ràng buộc & định dạng","Prompts have constraints & format"],["Được version & chia sẻ","Versioned & shared"]] }),
      T({ tv:"RAG: hỏi đáp trên tài liệu test nội bộ", te:"RAG: Q&A over internal test docs",
        sv:"Trợ lý AI trả lời dựa trên tài liệu/chuẩn của công ty.", se:"An AI assistant answering from company docs/standards.",
        ov:"Hiểu cách RAG giúp QA tra cứu chuẩn & lịch sử nhanh.", oe:"Understand how RAG helps QA look up standards & history fast.",
        cv:"RAG (Retrieval-Augmented Generation) nạp tài liệu vào vector store, AI truy hồi ngữ cảnh liên quan rồi trả lời — giảm ảo giác.", ce:"RAG loads docs into a vector store; the AI retrieves relevant context then answers — reducing hallucination.",
        st:[["Thu thập chuẩn test, bug lịch sử","Gather test standards, past bugs"],["Index vào vector store","Index into a vector store"],["Hỏi đáp có trích nguồn","Q&A with citations"],["Kiểm chứng câu trả lời quan trọng","Validate critical answers"]],
        ck:[["Câu trả lời có trích nguồn","Answers cite sources"],["Dữ liệu nội bộ được bảo mật","Internal data kept secure"]] }),
    ],
  },
];

// ---------------- MORE TOPICS appended to existing categories ----------------
export const MORE_TOPICS = {
  "ai-agent-testing": [
    T({ tv:"Thiết lập môi trường cho AI Agent test", te:"Setting up the environment for a testing AI agent",
      sv:"Chuẩn bị staging cô lập, dữ liệu giả & quyền tối thiểu.", se:"Prepare isolated staging, fake data & least privilege.",
      ov:"Dựng môi trường an toàn để agent khám phá và test.", oe:"Build a safe environment for an agent to explore and test.",
      cv:"Agent cần môi trường tách biệt production, dữ liệu ẩn danh, và ranh giới hành động rõ để tránh rủi ro phá huỷ.", ce:"An agent needs a non-production environment, anonymized data, and clear action boundaries to avoid destructive risk.",
      st:[["Tạo staging tách biệt production","Create staging isolated from production"],["Nạp dữ liệu giả/ẩn danh","Load fake/anonymized data"],["Cấp quyền tối thiểu (least privilege)","Grant least privilege"],["Định nghĩa hành động cấm","Define forbidden actions"]],
      ck:[["Không chạy trên production","Never runs on production"],["Quyền tối thiểu","Least privilege"]] }),
    T({ tv:"Cấu hình công cụ & MCP cho agent test", te:"Configuring tools & MCP for a testing agent",
      sv:"Kết nối trình duyệt, API, shell qua giao thức chuẩn.", se:"Connect browser, API, shell via a standard protocol.",
      ov:"Cấu hình bộ công cụ để agent hành động có kiểm soát.", oe:"Configure the toolset so the agent acts under control.",
      cv:"MCP (Model Context Protocol) cho phép cấp công cụ (browser, filesystem, API) cho agent một cách chuẩn hoá, có phạm vi & quyền.", ce:"MCP (Model Context Protocol) exposes tools (browser, filesystem, API) to an agent in a standardized, scoped, permissioned way.",
      st:[["Chọn công cụ cần thiết (browser/API)","Pick required tools (browser/API)"],["Cấu hình phạm vi & quyền từng công cụ","Configure scope & permission per tool"],["Thêm guardrail chặn hành động rủi ro","Add guardrails blocking risky actions"],["Log mọi hành động để audit","Log all actions for audit"]],
      ck:[["Mỗi công cụ có phạm vi rõ","Each tool has clear scope"],["Có log audit","Audit logging in place"]] }),
    T({ tv:"Triển khai agent test trong CI", te:"Deploying a testing agent in CI",
      sv:"Cho agent chạy tự động nhưng có cổng phê duyệt của người.", se:"Let the agent run automatically but with a human approval gate.",
      ov:"Đưa agent vào pipeline với guardrail & human-in-the-loop.", oe:"Integrate the agent into the pipeline with guardrails & human-in-the-loop.",
      cv:"Agent chạy theo trigger, đề xuất/chạy test, nhưng hành động rủi ro cần người duyệt; kết quả đưa vào report như test thường.", ce:"The agent runs on triggers, proposes/executes tests, but risky actions need human approval; results flow into reports like normal tests.",
      st:[["Đóng gói agent chạy trong container","Containerize the agent run"],["Đặt cổng phê duyệt cho hành động rủi ro","Gate risky actions for approval"],["Giới hạn thời gian & phạm vi mỗi lần chạy","Cap time & scope per run"],["Đưa kết quả vào report chuẩn","Feed results into standard reports"]],
      ck:[["Có human-in-the-loop","Human-in-the-loop present"],["Giới hạn thời gian/phạm vi","Time/scope capped"]] }),
    T({ tv:"Demo: agent tự khám phá & test một luồng", te:"Demo: an agent explores & tests a flow",
      sv:"Đi qua một buổi chạy agent thực tế từ đầu tới report.", se:"Walk through a real agent run from start to report.",
      ov:"Quan sát agent lập kế hoạch, hành động và tự đánh giá.", oe:"Observe the agent plan, act and self-evaluate.",
      cv:"Trong demo, agent nhận mục tiêu ('test luồng đăng ký'), tự điều hướng, phát hiện vấn đề, và tạo báo cáo — QA giám sát & xác nhận.", ce:"In the demo, the agent takes a goal ('test the signup flow'), navigates, finds issues, and produces a report — QA supervises & validates.",
      st:[["Giao mục tiêu rõ ràng cho agent","Give the agent a clear goal"],["Theo dõi kế hoạch & hành động","Watch the plan & actions"],["Xem phát hiện & bằng chứng","Review findings & evidence"],["Xác nhận, giữ ca giá trị","Validate, keep valuable cases"]],
      ck:[["Mục tiêu & phạm vi rõ","Clear goal & scope"],["Người xác nhận kết quả","Human validates results"]] }),
  ],
  "manual-testing": [
    T({ tv:"Kiểm thử khả năng truy cập (Accessibility/a11y)", te:"Accessibility (a11y) testing",
      sv:"Đảm bảo sản phẩm dùng được cho người khuyết tật (WCAG).", se:"Ensure the product is usable by people with disabilities (WCAG).",
      ov:"Kiểm tra tương phản, bàn phím, screen reader theo WCAG.", oe:"Check contrast, keyboard, screen readers per WCAG.",
      cv:"A11y testing xác minh tuân thủ WCAG: tương phản màu, điều hướng bàn phím, ARIA, alt text — vừa đạo đức vừa yêu cầu pháp lý ở nhiều nơi.", ce:"A11y testing verifies WCAG compliance: color contrast, keyboard nav, ARIA, alt text — both ethical and legally required in many regions.",
      st:[["Kiểm điều hướng chỉ bằng bàn phím","Test keyboard-only navigation"],["Đo tương phản màu","Measure color contrast"],["Thử với screen reader","Try a screen reader"],["Dùng axe/Lighthouse quét tự động","Use axe/Lighthouse to auto-scan"]],
      ck:[["Điều hướng bàn phím đủ","Full keyboard navigation"],["Tương phản đạt WCAG AA","Contrast meets WCAG AA"]] }),
    T({ tv:"Kiểm thử tương thích đa trình duyệt & thiết bị", te:"Cross-browser & device compatibility testing",
      sv:"Sản phẩm chạy nhất quán trên các trình duyệt/độ phân giải.", se:"Consistent behavior across browsers/resolutions.",
      ov:"Lập ma trận trình duyệt/thiết bị và test hiệu quả.", oe:"Build a browser/device matrix and test efficiently.",
      cv:"Xác định ma trận ưu tiên theo analytics người dùng thật, test trên thiết bị thật/cloud, tập trung khác biệt render.", ce:"Define a priority matrix from real user analytics, test on real/cloud devices, focus on rendering differences.",
      st:[["Lập ma trận từ dữ liệu người dùng","Build the matrix from user data"],["Ưu tiên trình duyệt/thiết bị phổ biến","Prioritize popular browsers/devices"],["Dùng cloud device (BrowserStack)","Use cloud devices (BrowserStack)"],["Ghi lại khác biệt render","Log rendering differences"]],
      ck:[["Ma trận dựa dữ liệu thật","Data-driven matrix"],["Test trên thiết bị thật","Tested on real devices"]] }),
    T({ tv:"Exploratory testing có kỷ luật (charter & SBTM)", te:"Disciplined exploratory testing (charters & SBTM)",
      sv:"Khám phá tự do nhưng có mục tiêu, thời hộp và ghi chép.", se:"Free exploration with goals, time-boxes and notes.",
      ov:"Dùng charter & session-based test management để khám phá hiệu quả.", oe:"Use charters & session-based test management to explore effectively.",
      cv:"SBTM tổ chức exploratory thành session có charter (mục tiêu), thời hộp 60–90', và ghi chú/bug — vừa linh hoạt vừa truy vết được.", ce:"SBTM organizes exploratory testing into chartered sessions (goals), 60–90' time-boxes, and notes/bugs — flexible yet traceable.",
      st:[["Viết charter cho mỗi session","Write a charter per session"],["Thời hộp 60–90 phút","Time-box 60–90 minutes"],["Ghi chú phát hiện & câu hỏi","Note findings & questions"],["Debrief & lập ca test mới","Debrief & spin off new tests"]],
      ck:[["Mỗi session có charter","Each session has a charter"],["Có ghi chép để truy vết","Notes kept for traceability"]] }),
  ],
  "automation-testing": [
    T({ tv:"Data-driven & keyword-driven framework", te:"Data-driven & keyword-driven frameworks",
      sv:"Tách dữ liệu/hành động khỏi code để mở rộng độ phủ.", se:"Separate data/actions from code to scale coverage.",
      ov:"Chọn kiểu framework phù hợp quy mô & kỹ năng team.", oe:"Pick the framework style fitting team scale & skills.",
      cv:"Data-driven lặp kịch bản với nhiều dữ liệu; keyword-driven trừu tượng hành động thành từ khoá cho người ít code.", ce:"Data-driven repeats a script over data sets; keyword-driven abstracts actions into keywords for low-code users.",
      st:[["Tách dữ liệu ra file/nguồn ngoài","Externalize data to files/sources"],["Tham số hoá test","Parameterize tests"],["Định nghĩa từ khoá tái dùng","Define reusable keywords"],["Cân nhắc chi phí bảo trì","Weigh maintenance cost"]],
      ck:[["Dữ liệu tách khỏi logic","Data separated from logic"],["Dễ thêm ca mới","Easy to add cases"]] }),
    T({ tv:"Chạy song song & tối ưu thời gian CI", te:"Parallel execution & CI time optimization",
      sv:"Rút ngắn phản hồi bằng song song, shard và setup qua API.", se:"Shorten feedback via parallelism, sharding and API setup.",
      ov:"Giảm thời gian bộ test mà vẫn ổn định.", oe:"Cut suite time while keeping it stable.",
      cv:"Song song hoá yêu cầu test độc lập & dữ liệu cô lập; sharding chia cho nhiều máy; setup qua API nhanh hơn UI.", ce:"Parallelism requires independent tests & isolated data; sharding splits across machines; API setup beats UI setup.",
      st:[["Đảm bảo test độc lập","Ensure test independence"],["Cô lập dữ liệu mỗi test","Isolate data per test"],["Shard trên nhiều runner","Shard across runners"],["Seed dữ liệu qua API","Seed data via API"]],
      ck:[["Test độc lập & song song được","Independent & parallel-safe"],["Setup qua API","API-based setup"]] }),
    T({ tv:"Contract testing với Pact", te:"Contract testing with Pact",
      sv:"Bắt lỗi tích hợp giữa service mà không cần E2E đầy đủ.", se:"Catch integration breaks between services without full E2E.",
      ov:"Hiểu consumer-driven contract để test microservices.", oe:"Understand consumer-driven contracts for microservices.",
      cv:"Pact ghi 'hợp đồng' kỳ vọng của consumer về API provider; provider verify hợp đồng — phát hiện phá vỡ tích hợp sớm.", ce:"Pact records the consumer's expected 'contract' of the provider API; the provider verifies it — catching integration breaks early.",
      st:[["Consumer định nghĩa kỳ vọng (pact)","Consumer defines expectations (pact)"],["Publish pact lên broker","Publish the pact to a broker"],["Provider verify pact trong CI","Provider verifies the pact in CI"],["Chặn deploy nếu phá hợp đồng","Block deploy on contract break"]],
      ck:[["Hợp đồng được verify trong CI","Contract verified in CI"],["Phát hiện phá vỡ sớm","Early break detection"]] }),
  ],
  "playwright-tools": [
    T({ tv:"Mock & chặn network trong Playwright", te:"Network mocking & interception in Playwright",
      sv:"Kiểm soát API để test ổn định, nhanh, không phụ thuộc backend.", se:"Control APIs for stable, fast, backend-independent tests.",
      ov:"Dùng route/fulfill để giả lập phản hồi API.", oe:"Use route/fulfill to stub API responses.",
      cv:"page.route cho phép chặn request và trả về dữ liệu giả — hữu ích test trạng thái lỗi, rỗng, tải chậm.", ce:"page.route intercepts requests and returns stubbed data — great for testing error, empty, slow states.",
      st:[["page.route('**/api/**', ...)","page.route('**/api/**', ...)"],["fulfill với JSON giả","fulfill with stubbed JSON"],["Test trạng thái lỗi/rỗng","Test error/empty states"],["Kết hợp test thật cho luồng chính","Combine with real tests for happy path"]],
      ck:[["Mock cho trạng thái khó tái hiện","Mock hard-to-reproduce states"],["Vẫn có test thật cho core","Keep real tests for core"]],
      exv:"Giả lập API sản phẩm trả về danh sách rỗng.", exe:"Stub the products API to return an empty list.",
      code:"await page.route('**/api/products', route =>\n  route.fulfill({ status: 200, body: JSON.stringify([]) })\n);\nawait page.goto('/products');\nawait expect(page.getByText('No products')).toBeVisible();" }),
    T({ tv:"Component testing với Playwright", te:"Component testing with Playwright",
      sv:"Test component UI cô lập, nhanh hơn E2E đầy đủ.", se:"Test UI components in isolation, faster than full E2E.",
      ov:"Viết test mount component và tương tác trực tiếp.", oe:"Write tests that mount a component and interact directly.",
      cv:"Playwright component testing render component (React/Vue/Svelte) trong trình duyệt thật để test hành vi UI nhỏ, nhanh.", ce:"Playwright component testing renders a component (React/Vue/Svelte) in a real browser to test small UI behavior, fast.",
      st:[["Cấu hình experimental-ct","Configure experimental-ct"],["mount(<Component/>)","mount(<Component/>)"],["Tương tác & assert web-first","Interact & web-first assert"],["Dùng cho design system","Use for the design system"]],
      ck:[["Test component cô lập","Isolated component tests"],["Nhanh & ổn định","Fast & stable"]] }),
    T({ tv:"Visual snapshot trong Playwright", te:"Visual snapshots in Playwright",
      sv:"toHaveScreenshot bắt lỗi giao diện tích hợp sẵn.", se:"Built-in toHaveScreenshot catches UI regressions.",
      ov:"Dùng snapshot ảnh có sẵn để phát hiện thay đổi giao diện.", oe:"Use built-in image snapshots to detect UI changes.",
      cv:"expect(page).toHaveScreenshot() so sánh với baseline; cần ổn định font/animation/dữ liệu để tránh nhiễu.", ce:"expect(page).toHaveScreenshot() compares to a baseline; stabilize fonts/animations/data to avoid noise.",
      st:[["Tắt animation & cố định dữ liệu","Disable animations & fix data"],["Chụp baseline lần đầu","Capture baseline first run"],["Duyệt & cập nhật khi đổi có chủ đích","Review & update on intentional change"],["Chạy trong CI đồng nhất OS","Run in CI with consistent OS"]],
      ck:[["Ổn định trước khi chụp","Stabilized before snapshot"],["Baseline theo cùng môi trường","Baseline on same environment"]] }),
  ],
  "ai-in-testing": [
    T({ tv:"Phát hiện flaky test bằng AI/thống kê", te:"AI/statistical flaky-test detection",
      sv:"Tự động nhận diện test không ổn định để cách ly & sửa.", se:"Automatically flag unstable tests to quarantine & fix.",
      ov:"Dùng lịch sử chạy để phát hiện & xử lý flaky sớm.", oe:"Use run history to detect & handle flakiness early.",
      cv:"Phân tích tỉ lệ pass/fail theo thời gian trên cùng commit để nhận diện flaky; AI gợi ý nguyên nhân (timing/dữ liệu).", ce:"Analyze pass/fail rates over time on the same commit to spot flakiness; AI suggests causes (timing/data).",
      st:[["Thu thập lịch sử chạy test","Collect test run history"],["Tính flaky rate mỗi test","Compute per-test flaky rate"],["Cách ly test flaky (quarantine)","Quarantine flaky tests"],["Sửa gốc & đưa lại vào suite","Fix root cause & re-add"]],
      ck:[["Theo dõi flaky rate","Track flaky rate"],["Có quy trình cách ly","Quarantine process exists"]] }),
    T({ tv:"AI hỗ trợ bảo trì test khi UI/luồng đổi", te:"AI-assisted test maintenance on UI/flow change",
      sv:"Giảm gánh nặng cập nhật test khi sản phẩm thay đổi nhanh.", se:"Reduce the burden of updating tests as the product changes fast.",
      ov:"Dùng AI đề xuất bản vá test theo diff của ứng dụng.", oe:"Use AI to propose test patches from the app diff.",
      cv:"AI đọc thay đổi UI/DOM & test hiện có để đề xuất cập nhật locator/bước — người review trước khi áp dụng.", ce:"AI reads UI/DOM changes & existing tests to propose locator/step updates — human reviews before applying.",
      st:[["Cung cấp diff UI cho AI","Provide the UI diff to AI"],["Nhận đề xuất cập nhật test","Get suggested test updates"],["Review & áp dụng có chọn lọc","Review & apply selectively"],["Chạy lại xác nhận","Re-run to confirm"]],
      ck:[["Có review trước khi áp","Reviewed before applying"],["Chạy lại xác nhận","Re-run confirmed"]] }),
  ],
  "claude-testing": [
    T({ tv:"Cấu hình MCP để Claude thao tác test", te:"Configuring MCP for Claude to run testing tasks",
      sv:"Cấp công cụ (browser, file, API) cho Claude một cách an toàn.", se:"Grant tools (browser, file, API) to Claude safely.",
      ov:"Thiết lập MCP server để Claude hỗ trợ QA có kiểm soát.", oe:"Set up MCP servers so Claude assists QA under control.",
      cv:"MCP kết nối Claude với công cụ ngoài theo chuẩn; QA chọn công cụ, phạm vi & quyền, giữ human phê duyệt.", ce:"MCP connects Claude to external tools via a standard; QA picks tools, scope & permissions, keeping human approval.",
      st:[["Chọn MCP cần (browser/filesystem/API)","Pick needed MCPs (browser/filesystem/API)"],["Giới hạn phạm vi & quyền","Limit scope & permissions"],["Thử trên staging","Trial on staging"],["Ghi log & review","Log & review"]],
      ck:[["Quyền tối thiểu","Least privilege"],["Có log & review","Logging & review"]] }),
    T({ tv:"Xây bộ prompt/skill QA cho Claude", te:"Building QA prompts/skills for Claude",
      sv:"Đóng gói quy trình QA thành skill tái dùng cho cả team.", se:"Package QA workflows into reusable team skills.",
      ov:"Chuẩn hoá cách Claude sinh test/bug theo chuẩn công ty.", oe:"Standardize how Claude generates tests/bugs to company standards.",
      cv:"Skill/prompt gói template + ví dụ few-shot + ràng buộc định dạng, để output nhất quán và đúng 'gu' team.", ce:"A skill/prompt bundles a template + few-shot examples + format constraints for consistent, on-brand output.",
      st:[["Xác định quy trình lặp lại","Identify repetitive workflows"],["Đóng gói prompt + ví dụ","Package prompt + examples"],["Kiểm thử trên ca thật","Test on real cases"],["Chia sẻ & version","Share & version"]],
      ck:[["Output nhất quán","Consistent output"],["Được team tái dùng","Reused by the team"]] }),
  ],
  "performance-api": [
    T({ tv:"Kiểm thử bảo mật API cơ bản cho QA", te:"Basic API security testing for QA",
      sv:"Bắt lỗi phân quyền, injection, lộ dữ liệu ngay từ tầng QA.", se:"Catch authz, injection, data-exposure issues at the QA layer.",
      ov:"Kiểm các rủi ro bảo mật phổ biến (OWASP API Top 10) khi test.", oe:"Check common security risks (OWASP API Top 10) during testing.",
      cv:"QA có thể phát hiện lỗi phân quyền (BOLA), thiếu rate limit, lộ dữ liệu, input không kiểm soát — trước khi tới pentest.", ce:"QA can catch broken authorization (BOLA), missing rate limits, data exposure, unvalidated input — before pentest.",
      st:[["Test truy cập tài nguyên không thuộc user","Test accessing another user's resource"],["Kiểm token hết hạn/không hợp lệ","Test expired/invalid tokens"],["Thử input độc hại (injection)","Try malicious input (injection)"],["Kiểm rate limit & lộ dữ liệu","Check rate limits & data exposure"]],
      ck:[["Test phân quyền chéo user","Cross-user authz tested"],["Kiểm token & input","Token & input checks"]] }),
  ],
};
